// Copyright 2026 Canonical Ltd. All rights reserved.
// Licensed under the AGPLv3, see LICENCE file for details.

// Code generated by go generate; DO NOT EDIT.

package modelimport

import (
	"github.com/juju/juju/domain/export/types/v4_0_4"
	"github.com/juju/juju/domain/export/types/v4_1_0"
	"github.com/juju/juju/domain/modelimport/adapter"
	"github.com/juju/juju/domain/modelimport/adapter/transforms/v4_0_4_to_v4_1_0"
)

// registered is the canonical list of version-to-version transformers
// the controller knows about. It is consumed by NewAdapter (in
// modelimport.go) alongside export.ExportVersions.
var registered = []adapter.Registration{
	adapter.Register[v4_0_4.ModelExport, v4_1_0.ModelExport](
		"4.0.4", "4.1.0",
		v4_0_4_to_v4_1_0.NewTransform(v4_0_4_to_v4_1_0.NewDeltas()),
	),
}
