// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/internal/controllerinit (interfaces: AgentPasswordService)
//
// Generated by this command:
//
//	mockgen -package controllerinit -destination agentpasswordservice_mock_test.go github.com/juju/juju/internal/controllerinit AgentPasswordService
//

// Package controllerinit is a generated GoMock package.
package controllerinit

import (
	context "context"

	gomock "github.com/canonical/gomock/gomock"
	application "github.com/juju/juju/core/application"
	machine "github.com/juju/juju/core/machine"
	unit "github.com/juju/juju/core/unit"
)

// MockAgentPasswordService is a mock of AgentPasswordService interface.
type MockAgentPasswordService struct {
	ctrl     *gomock.Controller
	recorder *MockAgentPasswordServiceMockRecorder
	isgomock struct{}
}

// MockAgentPasswordServiceMockRecorder is the mock recorder for MockAgentPasswordService.
type MockAgentPasswordServiceMockRecorder struct {
	mock                             *MockAgentPasswordService
	ensureControllerNodeNonceExpects []*gomock.Call3_2[context.Context, string, string, string, error]
	setApplicationPasswordExpects    []*gomock.Call3_1[context.Context, application.UUID, string, error]
	setControllerNodePasswordExpects []*gomock.Call3_1[context.Context, string, string, error]
	setMachinePasswordExpects        []*gomock.Call3_1[context.Context, machine.Name, string, error]
	setUnitPasswordExpects           []*gomock.Call3_1[context.Context, unit.Name, string, error]
}

// NewMockAgentPasswordService creates a new mock instance.
func NewMockAgentPasswordService(ctrl *gomock.Controller) *MockAgentPasswordService {
	mock := &MockAgentPasswordService{ctrl: ctrl}
	mock.recorder = &MockAgentPasswordServiceMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentPasswordService) EXPECT() *MockAgentPasswordServiceMockRecorder {
	return m.recorder
}

// EnsureControllerNodeNonce mocks base method.
func (m *MockAgentPasswordService) EnsureControllerNodeNonce(ctx context.Context, controllerID, nonce string) (string, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_2(&m.recorder.ensureControllerNodeNonceExpects, m.ctrl, m, "EnsureControllerNodeNonce", ctx, controllerID, nonce)
}

// EnsureControllerNodeNonce indicates an expected call of EnsureControllerNodeNonce.
func (mr *MockAgentPasswordServiceMockRecorder) EnsureControllerNodeNonce(ctx, controllerID, nonce any) *MockAgentPasswordServiceEnsureControllerNodeNonceCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_2[context.Context, string, string, string, error](mr.mock.ctrl.T, mr.mock, "EnsureControllerNodeNonce", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(controllerID), gomock.EnsureMatcher(nonce))
	mr.ensureControllerNodeNonceExpects = append(mr.ensureControllerNodeNonceExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockAgentPasswordServiceEnsureControllerNodeNonceCall is the typed call wrapper for EnsureControllerNodeNonce.
type MockAgentPasswordServiceEnsureControllerNodeNonceCall = gomock.Call3_2[context.Context, string, string, string, error]

// SetApplicationPassword mocks base method.
func (m *MockAgentPasswordService) SetApplicationPassword(ctx context.Context, appID application.UUID, password string) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_1(&m.recorder.setApplicationPasswordExpects, m.ctrl, m, "SetApplicationPassword", ctx, appID, password)
}

// SetApplicationPassword indicates an expected call of SetApplicationPassword.
func (mr *MockAgentPasswordServiceMockRecorder) SetApplicationPassword(ctx, appID, password any) *MockAgentPasswordServiceSetApplicationPasswordCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_1[context.Context, application.UUID, string, error](mr.mock.ctrl.T, mr.mock, "SetApplicationPassword", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(appID), gomock.EnsureMatcher(password))
	mr.setApplicationPasswordExpects = append(mr.setApplicationPasswordExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockAgentPasswordServiceSetApplicationPasswordCall is the typed call wrapper for SetApplicationPassword.
type MockAgentPasswordServiceSetApplicationPasswordCall = gomock.Call3_1[context.Context, application.UUID, string, error]

// SetControllerNodePassword mocks base method.
func (m *MockAgentPasswordService) SetControllerNodePassword(ctx context.Context, controllerID, password string) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_1(&m.recorder.setControllerNodePasswordExpects, m.ctrl, m, "SetControllerNodePassword", ctx, controllerID, password)
}

// SetControllerNodePassword indicates an expected call of SetControllerNodePassword.
func (mr *MockAgentPasswordServiceMockRecorder) SetControllerNodePassword(ctx, controllerID, password any) *MockAgentPasswordServiceSetControllerNodePasswordCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_1[context.Context, string, string, error](mr.mock.ctrl.T, mr.mock, "SetControllerNodePassword", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(controllerID), gomock.EnsureMatcher(password))
	mr.setControllerNodePasswordExpects = append(mr.setControllerNodePasswordExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockAgentPasswordServiceSetControllerNodePasswordCall is the typed call wrapper for SetControllerNodePassword.
type MockAgentPasswordServiceSetControllerNodePasswordCall = gomock.Call3_1[context.Context, string, string, error]

// SetMachinePassword mocks base method.
func (m *MockAgentPasswordService) SetMachinePassword(ctx context.Context, machineName machine.Name, password string) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_1(&m.recorder.setMachinePasswordExpects, m.ctrl, m, "SetMachinePassword", ctx, machineName, password)
}

// SetMachinePassword indicates an expected call of SetMachinePassword.
func (mr *MockAgentPasswordServiceMockRecorder) SetMachinePassword(ctx, machineName, password any) *MockAgentPasswordServiceSetMachinePasswordCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_1[context.Context, machine.Name, string, error](mr.mock.ctrl.T, mr.mock, "SetMachinePassword", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(machineName), gomock.EnsureMatcher(password))
	mr.setMachinePasswordExpects = append(mr.setMachinePasswordExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockAgentPasswordServiceSetMachinePasswordCall is the typed call wrapper for SetMachinePassword.
type MockAgentPasswordServiceSetMachinePasswordCall = gomock.Call3_1[context.Context, machine.Name, string, error]

// SetUnitPassword mocks base method.
func (m *MockAgentPasswordService) SetUnitPassword(ctx context.Context, unitName unit.Name, password string) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_1(&m.recorder.setUnitPasswordExpects, m.ctrl, m, "SetUnitPassword", ctx, unitName, password)
}

// SetUnitPassword indicates an expected call of SetUnitPassword.
func (mr *MockAgentPasswordServiceMockRecorder) SetUnitPassword(ctx, unitName, password any) *MockAgentPasswordServiceSetUnitPasswordCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_1[context.Context, unit.Name, string, error](mr.mock.ctrl.T, mr.mock, "SetUnitPassword", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(unitName), gomock.EnsureMatcher(password))
	mr.setUnitPasswordExpects = append(mr.setUnitPasswordExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockAgentPasswordServiceSetUnitPasswordCall is the typed call wrapper for SetUnitPassword.
type MockAgentPasswordServiceSetUnitPasswordCall = gomock.Call3_1[context.Context, unit.Name, string, error]
