// Copyright 2026 Canonical Ltd.
// Licensed under the AGPLv3, see LICENCE file for details.

package restore

// tablePolicy classifies how one dumped table is loaded into the freshly
// bootstrapped database.
type tablePolicy uint8

const (
	// policyInsert restores the dumped rows verbatim. This is the
	// default: the fresh database holds only seed rows, which are never
	// in this category, so a constraint violation means a corrupt or
	// inconsistent archive and fails the load.
	policyInsert tablePolicy = iota

	// policySkip keeps the target's bootstrapped content: static lookup
	// rows seeded by the schema (identical under the exact-version gate)
	// and runtime state that is regenerated, never imported stale.
	policySkip

	// policyMerge inserts rows with INSERT OR IGNORE for tables where
	// bootstrap seed rows and dumped rows legitimately overlap:
	// content-addressed object metadata and the seeded default space.
	policyMerge
)

// controllerTablePolicies are the non-default policies for the controller
// database. Every table not listed here is policyInsert.
var controllerTablePolicies = map[string]tablePolicy{
	// Static lookup rows seeded by the schema DDL.
	"architecture":                      policySkip,
	"auth_type":                         policySkip,
	"autocert_cache_encoding":           policySkip,
	"change_log_edit_type":              policySkip,
	"cloud_type":                        policySkip,
	"lease_type":                        policySkip,
	"life":                              policySkip,
	"model_migration_import_phase_type": policySkip,
	"model_migration_phase":             policySkip,
	"model_type":                        policySkip,
	"object_store_backend":              policySkip,
	"object_store_backend_type":         policySkip,
	"object_store_drain_phase_type":     policySkip,
	"password_hash_algorithm":           policySkip,
	"permission_access_type":            policySkip,
	"permission_object_access":          policySkip,
	"permission_object_type":            policySkip,
	"secret_backend_origin":             policySkip,
	"secret_backend_type":               policySkip,
	"ssh_fingerprint_hash_algorithm":    policySkip,
	"ssh_key_algorithm_type":            policySkip,
	"upgrade_state_type":                policySkip,

	// Runtime and node-local state: regenerated by the running
	// controller, never imported stale. controller_node and its
	// passwords/nonces describe the replacement and are bootstrapped or
	// finalized agent-side; controller_api_address is written from the
	// replacement's addresses; object_store_backend keeps the file
	// backend the replacement bootstrapped with (restore is always
	// file-backed); drain history is not carried over.
	"change_log":                     policySkip,
	"change_log_namespace":           policySkip,
	"change_log_witness":             policySkip,
	"controller_node":                policySkip,
	"controller_node_agent_version":  policySkip,
	"controller_node_nonce":          policySkip,
	"controller_node_password":       policySkip,
	"controller_api_address":         policySkip,
	"autocert_cache":                 policySkip,
	"upgrade_info":                   policySkip,
	"upgrade_info_controller_node":   policySkip,
	"object_store_backend_s3_config": policySkip,
	"object_store_drain_info":        policySkip,
	// The bootstrap flag gates the bootstrap worker: the archived flag
	// would uninstall the worker before it finalizes the replacement
	// (controller node password, API host ports, bootstrap unlock).
	"flag": policySkip,

	// Object metadata is content-addressed: the replacement's own
	// bootstrap blobs (agent binary, controller charm) collide with
	// identical archived rows on their hash unique indexes.
	"object_store_metadata":      policyMerge,
	"object_store_metadata_path": policyMerge,

	// The schema table records the migration versions the fresh DDL
	// already applied — identical under the exact-version gate, so keep
	// the target's rows rather than colliding on the primary key.
	"schema": policySkip,
}

// modelTablePolicies are the non-default policies for each model
// database. Every table not listed here is policyInsert.
var modelTablePolicies = map[string]tablePolicy{
	// Static lookup rows seeded by the schema DDL.
	"agent_stream":                        policySkip,
	"architecture":                        policySkip,
	"block_command_type":                  policySkip,
	"block_device_provenance":             policySkip,
	"change_log_edit_type":                policySkip,
	"charm_config_type":                   policySkip,
	"charm_provenance":                    policySkip,
	"charm_relation_role":                 policySkip,
	"charm_relation_scope":                policySkip,
	"charm_resource_kind":                 policySkip,
	"charm_run_as_kind":                   policySkip,
	"charm_source":                        policySkip,
	"charm_storage_kind":                  policySkip,
	"container_type":                      policySkip,
	"hash_kind":                           policySkip,
	"ip_address_config_type":              policySkip,
	"ip_address_origin":                   policySkip,
	"ip_address_scope":                    policySkip,
	"ip_address_type":                     policySkip,
	"k8s_pod_status_value":                policySkip,
	"life":                                policySkip,
	"link_layer_device_type":              policySkip,
	"machine_cloud_instance_status_value": policySkip,
	"machine_placement_scope":             policySkip,
	"machine_status_value":                policySkip,
	"network_address_scope":               policySkip,
	"operation_task_status_value":         policySkip,
	"os":                                  policySkip,
	"password_hash_algorithm":             policySkip,
	"protocol":                            policySkip,
	"relation_status_type":                policySkip,
	"removal_type":                        policySkip,
	"resolve_mode":                        policySkip,
	"resource_origin_type":                policySkip,
	"resource_retrieved_by_type":          policySkip,
	"resource_state":                      policySkip,
	"secret_grant_scope_type":             policySkip,
	"secret_grant_subject_type":           policySkip,
	"secret_role":                         policySkip,
	"secret_rotate_policy":                policySkip,
	"ssh_key_algorithm_type":              policySkip,
	"storage_filesystem_status_value":     policySkip,
	"storage_kind":                        policySkip,
	"storage_pool_origin":                 policySkip,
	"storage_provision_scope":             policySkip,
	"storage_volume_device_type":          policySkip,
	"storage_volume_status_value":         policySkip,
	"unit_agent_status_value":             policySkip,
	"virtual_port_type":                   policySkip,
	"workload_status_value":               policySkip,

	// Runtime change log: regenerated by the running controller.
	"change_log":           policySkip,
	"change_log_namespace": policySkip,
	"change_log_witness":   policySkip,

	// Runtime observations the first reconcile resyncs from the live
	// cluster / agents. Imported rows would describe the source's pods
	// and presence, not the replacement's: k8s pod and service
	// observations (unit uuid is the key; pod name and service
	// provider_id are re-observed by name), and agent presence
	// heartbeats.
	"k8s_pod":                policySkip,
	"k8s_pod_port":           policySkip,
	"k8s_pod_status":         policySkip,
	"k8s_service":            policySkip,
	"machine_agent_presence": policySkip,
	"unit_agent_presence":    policySkip,

	// The default "alpha" space is seeded at model creation and also
	// present in the dump with identical content; user-created spaces
	// merge in alongside it.
	"space": policyMerge,

	// Object metadata is content-addressed: identical archived rows
	// merge with any bootstrap-seeded rows on their hash unique indexes.
	"object_store_metadata":      policyMerge,
	"object_store_metadata_path": policyMerge,

	// The schema table records the migration versions the fresh model
	// DDL already applied — identical under the exact-version gate.
	"schema": policySkip,
}

// specialTables are handled outside the generic replay and must never be
// reached by it.
var specialTables = map[string]bool{
	// The seed row the replacement bootstrapped with is deleted and the
	// source row restored (nothing references controller.uuid).
	"controller": true,
	// Placements are rebuilt for the single replacement node after the
	// metadata merge.
	"object_store_placement": true,
}
