// Copyright 2026 Canonical Ltd. All rights reserved.
// Licensed under the AGPLv3, see LICENCE file for details.

// Code generated by go generate; DO NOT EDIT.

package controller

import (
	"testing"

	"github.com/juju/tc"

	"github.com/juju/juju/domain/export/types/controller/v4_1_0"
	schematesting "github.com/juju/juju/domain/schema/testing"
)

type importStateSuiteV4_1_0 struct {
	schematesting.ControllerModelSuite
}

func TestImportStateSuiteV4_1_0(t *testing.T) {
	tc.Run(t, &importStateSuiteV4_1_0{})
}

// TestImportEmptyPayloadIsNoOp asserts that importing a payload with no rows
// in any content table succeeds without writing anything. Overlay and other
// business-logic corrections are hand-written, not generated, and are
// exercised in overlay tests.
func (s *importStateSuiteV4_1_0) TestImportEmptyPayloadIsNoOp(c *tc.C) {
	st := NewState(s.TxnRunnerFactory())
	err := st.Import(c.Context(), &v4_1_0.ControllerExport{})
	c.Assert(err, tc.ErrorIsNil)
}
