// Copyright 2026 Canonical Ltd. All rights reserved.
// Licensed under the AGPLv3, see LICENCE file for details.

// Code generated by go generate; DO NOT EDIT.

package controller

import (
	"context"

	"github.com/canonical/sqlair"

	"github.com/juju/juju/domain/export/types/controller/v4_1_0"
	"github.com/juju/juju/internal/errors"
)

// Import inserts all controller data carried by the source
// payload for version 4.1.0 into the target DB. It is the
// write-mirror of the generated export state: each ordinary content table is
// wiped and then bulk-inserted from the matching payload slice, so the source
// logical state wins over any rows the target bootstrap seeded (e.g. the
// fresh cloud/credential rows carry the same names as the source's). All
// deletes and inserts run in one transaction with FK checks deferred to
// commit, so ordering does not matter. Target-local tables (controller
// node/config, changelog, schema, namespace_list, object store backend/drain,
// secret backend) are excluded from import and handled by the overlay phase;
// seeded tables are inserted with ON CONFLICT DO NOTHING so their identical
// seed rows are skipped while genuine content rows are kept.
//
// Import is purely mechanical and contains no Juju-specific business logic.
// Corrections that ARE business logic (target-local overlay, secret backend
// remapping, changelog/lease cleanup, object-store placement) are
// hand-written, not generated, and run afterwards once this transaction has
// committed.
func (st *State) Import(ctx context.Context, p *v4_1_0.ControllerExport) error {
	// Prepare statements first using the typed samples from the generated types package.
	stmtAgentBinaryStore, err := sqlair.Prepare(`INSERT INTO "agent_binary_store" (*) VALUES ($AgentBinaryStore.*)`, v4_1_0.AgentBinaryStore{})
	if err != nil {
		return errors.Errorf("preparing AgentBinaryStore insert statement: %w", err)
	}
	stmtDeleteAgentBinaryStore, err := sqlair.Prepare(`DELETE FROM "agent_binary_store"`)
	if err != nil {
		return errors.Errorf("preparing AgentBinaryStore delete statement: %w", err)
	}
	stmtArchitecture, err := sqlair.Prepare(`INSERT INTO "architecture" (*) VALUES ($Architecture.*) ON CONFLICT DO NOTHING`, v4_1_0.Architecture{})
	if err != nil {
		return errors.Errorf("preparing Architecture insert statement: %w", err)
	}
	stmtAuthType, err := sqlair.Prepare(`INSERT INTO "auth_type" (*) VALUES ($AuthType.*) ON CONFLICT DO NOTHING`, v4_1_0.AuthType{})
	if err != nil {
		return errors.Errorf("preparing AuthType insert statement: %w", err)
	}
	stmtAutocertCache, err := sqlair.Prepare(`INSERT INTO "autocert_cache" (*) VALUES ($AutocertCache.*)`, v4_1_0.AutocertCache{})
	if err != nil {
		return errors.Errorf("preparing AutocertCache insert statement: %w", err)
	}
	stmtDeleteAutocertCache, err := sqlair.Prepare(`DELETE FROM "autocert_cache"`)
	if err != nil {
		return errors.Errorf("preparing AutocertCache delete statement: %w", err)
	}
	stmtAutocertCacheEncoding, err := sqlair.Prepare(`INSERT INTO "autocert_cache_encoding" (*) VALUES ($AutocertCacheEncoding.*) ON CONFLICT DO NOTHING`, v4_1_0.AutocertCacheEncoding{})
	if err != nil {
		return errors.Errorf("preparing AutocertCacheEncoding insert statement: %w", err)
	}
	stmtBakeryConfig, err := sqlair.Prepare(`INSERT INTO "bakery_config" (*) VALUES ($BakeryConfig.*)`, v4_1_0.BakeryConfig{})
	if err != nil {
		return errors.Errorf("preparing BakeryConfig insert statement: %w", err)
	}
	stmtDeleteBakeryConfig, err := sqlair.Prepare(`DELETE FROM "bakery_config"`)
	if err != nil {
		return errors.Errorf("preparing BakeryConfig delete statement: %w", err)
	}
	stmtCharmTracingConfig, err := sqlair.Prepare(`INSERT INTO "charm_tracing_config" (*) VALUES ($CharmTracingConfig.*)`, v4_1_0.CharmTracingConfig{})
	if err != nil {
		return errors.Errorf("preparing CharmTracingConfig insert statement: %w", err)
	}
	stmtDeleteCharmTracingConfig, err := sqlair.Prepare(`DELETE FROM "charm_tracing_config"`)
	if err != nil {
		return errors.Errorf("preparing CharmTracingConfig delete statement: %w", err)
	}
	stmtCloud, err := sqlair.Prepare(`INSERT INTO "cloud" (*) VALUES ($Cloud.*)`, v4_1_0.Cloud{})
	if err != nil {
		return errors.Errorf("preparing Cloud insert statement: %w", err)
	}
	stmtDeleteCloud, err := sqlair.Prepare(`DELETE FROM "cloud"`)
	if err != nil {
		return errors.Errorf("preparing Cloud delete statement: %w", err)
	}
	stmtCloudAuthType, err := sqlair.Prepare(`INSERT INTO "cloud_auth_type" (*) VALUES ($CloudAuthType.*)`, v4_1_0.CloudAuthType{})
	if err != nil {
		return errors.Errorf("preparing CloudAuthType insert statement: %w", err)
	}
	stmtDeleteCloudAuthType, err := sqlair.Prepare(`DELETE FROM "cloud_auth_type"`)
	if err != nil {
		return errors.Errorf("preparing CloudAuthType delete statement: %w", err)
	}
	stmtCloudCaCert, err := sqlair.Prepare(`INSERT INTO "cloud_ca_cert" (*) VALUES ($CloudCaCert.*)`, v4_1_0.CloudCaCert{})
	if err != nil {
		return errors.Errorf("preparing CloudCaCert insert statement: %w", err)
	}
	stmtDeleteCloudCaCert, err := sqlair.Prepare(`DELETE FROM "cloud_ca_cert"`)
	if err != nil {
		return errors.Errorf("preparing CloudCaCert delete statement: %w", err)
	}
	stmtCloudCredential, err := sqlair.Prepare(`INSERT INTO "cloud_credential" (*) VALUES ($CloudCredential.*)`, v4_1_0.CloudCredential{})
	if err != nil {
		return errors.Errorf("preparing CloudCredential insert statement: %w", err)
	}
	stmtDeleteCloudCredential, err := sqlair.Prepare(`DELETE FROM "cloud_credential"`)
	if err != nil {
		return errors.Errorf("preparing CloudCredential delete statement: %w", err)
	}
	stmtCloudCredentialAttribute, err := sqlair.Prepare(`INSERT INTO "cloud_credential_attribute" (*) VALUES ($CloudCredentialAttribute.*)`, v4_1_0.CloudCredentialAttribute{})
	if err != nil {
		return errors.Errorf("preparing CloudCredentialAttribute insert statement: %w", err)
	}
	stmtDeleteCloudCredentialAttribute, err := sqlair.Prepare(`DELETE FROM "cloud_credential_attribute"`)
	if err != nil {
		return errors.Errorf("preparing CloudCredentialAttribute delete statement: %w", err)
	}
	stmtCloudDefaults, err := sqlair.Prepare(`INSERT INTO "cloud_defaults" (*) VALUES ($CloudDefaults.*)`, v4_1_0.CloudDefaults{})
	if err != nil {
		return errors.Errorf("preparing CloudDefaults insert statement: %w", err)
	}
	stmtDeleteCloudDefaults, err := sqlair.Prepare(`DELETE FROM "cloud_defaults"`)
	if err != nil {
		return errors.Errorf("preparing CloudDefaults delete statement: %w", err)
	}
	stmtCloudImageMetadata, err := sqlair.Prepare(`INSERT INTO "cloud_image_metadata" (*) VALUES ($CloudImageMetadata.*)`, v4_1_0.CloudImageMetadata{})
	if err != nil {
		return errors.Errorf("preparing CloudImageMetadata insert statement: %w", err)
	}
	stmtDeleteCloudImageMetadata, err := sqlair.Prepare(`DELETE FROM "cloud_image_metadata"`)
	if err != nil {
		return errors.Errorf("preparing CloudImageMetadata delete statement: %w", err)
	}
	stmtCloudRegion, err := sqlair.Prepare(`INSERT INTO "cloud_region" (*) VALUES ($CloudRegion.*)`, v4_1_0.CloudRegion{})
	if err != nil {
		return errors.Errorf("preparing CloudRegion insert statement: %w", err)
	}
	stmtDeleteCloudRegion, err := sqlair.Prepare(`DELETE FROM "cloud_region"`)
	if err != nil {
		return errors.Errorf("preparing CloudRegion delete statement: %w", err)
	}
	stmtCloudRegionDefaults, err := sqlair.Prepare(`INSERT INTO "cloud_region_defaults" (*) VALUES ($CloudRegionDefaults.*)`, v4_1_0.CloudRegionDefaults{})
	if err != nil {
		return errors.Errorf("preparing CloudRegionDefaults insert statement: %w", err)
	}
	stmtDeleteCloudRegionDefaults, err := sqlair.Prepare(`DELETE FROM "cloud_region_defaults"`)
	if err != nil {
		return errors.Errorf("preparing CloudRegionDefaults delete statement: %w", err)
	}
	stmtCloudType, err := sqlair.Prepare(`INSERT INTO "cloud_type" (*) VALUES ($CloudType.*) ON CONFLICT DO NOTHING`, v4_1_0.CloudType{})
	if err != nil {
		return errors.Errorf("preparing CloudType insert statement: %w", err)
	}
	stmtExternalController, err := sqlair.Prepare(`INSERT INTO "external_controller" (*) VALUES ($ExternalController.*)`, v4_1_0.ExternalController{})
	if err != nil {
		return errors.Errorf("preparing ExternalController insert statement: %w", err)
	}
	stmtDeleteExternalController, err := sqlair.Prepare(`DELETE FROM "external_controller"`)
	if err != nil {
		return errors.Errorf("preparing ExternalController delete statement: %w", err)
	}
	stmtExternalControllerAddress, err := sqlair.Prepare(`INSERT INTO "external_controller_address" (*) VALUES ($ExternalControllerAddress.*)`, v4_1_0.ExternalControllerAddress{})
	if err != nil {
		return errors.Errorf("preparing ExternalControllerAddress insert statement: %w", err)
	}
	stmtDeleteExternalControllerAddress, err := sqlair.Prepare(`DELETE FROM "external_controller_address"`)
	if err != nil {
		return errors.Errorf("preparing ExternalControllerAddress delete statement: %w", err)
	}
	stmtExternalModel, err := sqlair.Prepare(`INSERT INTO "external_model" (*) VALUES ($ExternalModel.*)`, v4_1_0.ExternalModel{})
	if err != nil {
		return errors.Errorf("preparing ExternalModel insert statement: %w", err)
	}
	stmtDeleteExternalModel, err := sqlair.Prepare(`DELETE FROM "external_model"`)
	if err != nil {
		return errors.Errorf("preparing ExternalModel delete statement: %w", err)
	}
	stmtFlag, err := sqlair.Prepare(`INSERT INTO "flag" (*) VALUES ($Flag.*)`, v4_1_0.Flag{})
	if err != nil {
		return errors.Errorf("preparing Flag insert statement: %w", err)
	}
	stmtDeleteFlag, err := sqlair.Prepare(`DELETE FROM "flag"`)
	if err != nil {
		return errors.Errorf("preparing Flag delete statement: %w", err)
	}
	stmtLease, err := sqlair.Prepare(`INSERT INTO "lease" (*) VALUES ($Lease.*)`, v4_1_0.Lease{})
	if err != nil {
		return errors.Errorf("preparing Lease insert statement: %w", err)
	}
	stmtDeleteLease, err := sqlair.Prepare(`DELETE FROM "lease"`)
	if err != nil {
		return errors.Errorf("preparing Lease delete statement: %w", err)
	}
	stmtLeasePin, err := sqlair.Prepare(`INSERT INTO "lease_pin" (*) VALUES ($LeasePin.*)`, v4_1_0.LeasePin{})
	if err != nil {
		return errors.Errorf("preparing LeasePin insert statement: %w", err)
	}
	stmtDeleteLeasePin, err := sqlair.Prepare(`DELETE FROM "lease_pin"`)
	if err != nil {
		return errors.Errorf("preparing LeasePin delete statement: %w", err)
	}
	stmtLeaseType, err := sqlair.Prepare(`INSERT INTO "lease_type" (*) VALUES ($LeaseType.*) ON CONFLICT DO NOTHING`, v4_1_0.LeaseType{})
	if err != nil {
		return errors.Errorf("preparing LeaseType insert statement: %w", err)
	}
	stmtLife, err := sqlair.Prepare(`INSERT INTO "life" (*) VALUES ($Life.*) ON CONFLICT DO NOTHING`, v4_1_0.Life{})
	if err != nil {
		return errors.Errorf("preparing Life insert statement: %w", err)
	}
	stmtLoggingLokiConfig, err := sqlair.Prepare(`INSERT INTO "logging_loki_config" (*) VALUES ($LoggingLokiConfig.*)`, v4_1_0.LoggingLokiConfig{})
	if err != nil {
		return errors.Errorf("preparing LoggingLokiConfig insert statement: %w", err)
	}
	stmtDeleteLoggingLokiConfig, err := sqlair.Prepare(`DELETE FROM "logging_loki_config"`)
	if err != nil {
		return errors.Errorf("preparing LoggingLokiConfig delete statement: %w", err)
	}
	stmtMacaroonRootKey, err := sqlair.Prepare(`INSERT INTO "macaroon_root_key" (*) VALUES ($MacaroonRootKey.*)`, v4_1_0.MacaroonRootKey{})
	if err != nil {
		return errors.Errorf("preparing MacaroonRootKey insert statement: %w", err)
	}
	stmtDeleteMacaroonRootKey, err := sqlair.Prepare(`DELETE FROM "macaroon_root_key"`)
	if err != nil {
		return errors.Errorf("preparing MacaroonRootKey delete statement: %w", err)
	}
	stmtModel, err := sqlair.Prepare(`INSERT INTO "model" (*) VALUES ($Model.*)`, v4_1_0.Model{})
	if err != nil {
		return errors.Errorf("preparing Model insert statement: %w", err)
	}
	stmtDeleteModel, err := sqlair.Prepare(`DELETE FROM "model"`)
	if err != nil {
		return errors.Errorf("preparing Model delete statement: %w", err)
	}
	stmtModelAuthorizedKeys, err := sqlair.Prepare(`INSERT INTO "model_authorized_keys" (*) VALUES ($ModelAuthorizedKeys.*)`, v4_1_0.ModelAuthorizedKeys{})
	if err != nil {
		return errors.Errorf("preparing ModelAuthorizedKeys insert statement: %w", err)
	}
	stmtDeleteModelAuthorizedKeys, err := sqlair.Prepare(`DELETE FROM "model_authorized_keys"`)
	if err != nil {
		return errors.Errorf("preparing ModelAuthorizedKeys delete statement: %w", err)
	}
	stmtModelDatabaseDeletion, err := sqlair.Prepare(`INSERT INTO "model_database_deletion" (*) VALUES ($ModelDatabaseDeletion.*)`, v4_1_0.ModelDatabaseDeletion{})
	if err != nil {
		return errors.Errorf("preparing ModelDatabaseDeletion insert statement: %w", err)
	}
	stmtDeleteModelDatabaseDeletion, err := sqlair.Prepare(`DELETE FROM "model_database_deletion"`)
	if err != nil {
		return errors.Errorf("preparing ModelDatabaseDeletion delete statement: %w", err)
	}
	stmtModelLastLogin, err := sqlair.Prepare(`INSERT INTO "model_last_login" (*) VALUES ($ModelLastLogin.*)`, v4_1_0.ModelLastLogin{})
	if err != nil {
		return errors.Errorf("preparing ModelLastLogin insert statement: %w", err)
	}
	stmtDeleteModelLastLogin, err := sqlair.Prepare(`DELETE FROM "model_last_login"`)
	if err != nil {
		return errors.Errorf("preparing ModelLastLogin delete statement: %w", err)
	}
	stmtModelMigrationExport, err := sqlair.Prepare(`INSERT INTO "model_migration_export" (*) VALUES ($ModelMigrationExport.*)`, v4_1_0.ModelMigrationExport{})
	if err != nil {
		return errors.Errorf("preparing ModelMigrationExport insert statement: %w", err)
	}
	stmtDeleteModelMigrationExport, err := sqlair.Prepare(`DELETE FROM "model_migration_export"`)
	if err != nil {
		return errors.Errorf("preparing ModelMigrationExport delete statement: %w", err)
	}
	stmtModelMigrationExportMinionSync, err := sqlair.Prepare(`INSERT INTO "model_migration_export_minion_sync" (*) VALUES ($ModelMigrationExportMinionSync.*)`, v4_1_0.ModelMigrationExportMinionSync{})
	if err != nil {
		return errors.Errorf("preparing ModelMigrationExportMinionSync insert statement: %w", err)
	}
	stmtDeleteModelMigrationExportMinionSync, err := sqlair.Prepare(`DELETE FROM "model_migration_export_minion_sync"`)
	if err != nil {
		return errors.Errorf("preparing ModelMigrationExportMinionSync delete statement: %w", err)
	}
	stmtModelMigrationExportOffer, err := sqlair.Prepare(`INSERT INTO "model_migration_export_offer" (*) VALUES ($ModelMigrationExportOffer.*)`, v4_1_0.ModelMigrationExportOffer{})
	if err != nil {
		return errors.Errorf("preparing ModelMigrationExportOffer insert statement: %w", err)
	}
	stmtDeleteModelMigrationExportOffer, err := sqlair.Prepare(`DELETE FROM "model_migration_export_offer"`)
	if err != nil {
		return errors.Errorf("preparing ModelMigrationExportOffer delete statement: %w", err)
	}
	stmtModelMigrationExportPhase, err := sqlair.Prepare(`INSERT INTO "model_migration_export_phase" (*) VALUES ($ModelMigrationExportPhase.*)`, v4_1_0.ModelMigrationExportPhase{})
	if err != nil {
		return errors.Errorf("preparing ModelMigrationExportPhase insert statement: %w", err)
	}
	stmtDeleteModelMigrationExportPhase, err := sqlair.Prepare(`DELETE FROM "model_migration_export_phase"`)
	if err != nil {
		return errors.Errorf("preparing ModelMigrationExportPhase delete statement: %w", err)
	}
	stmtModelMigrationExportStatus, err := sqlair.Prepare(`INSERT INTO "model_migration_export_status" (*) VALUES ($ModelMigrationExportStatus.*)`, v4_1_0.ModelMigrationExportStatus{})
	if err != nil {
		return errors.Errorf("preparing ModelMigrationExportStatus insert statement: %w", err)
	}
	stmtDeleteModelMigrationExportStatus, err := sqlair.Prepare(`DELETE FROM "model_migration_export_status"`)
	if err != nil {
		return errors.Errorf("preparing ModelMigrationExportStatus delete statement: %w", err)
	}
	stmtModelMigrationExportTargetAuth, err := sqlair.Prepare(`INSERT INTO "model_migration_export_target_auth" (*) VALUES ($ModelMigrationExportTargetAuth.*)`, v4_1_0.ModelMigrationExportTargetAuth{})
	if err != nil {
		return errors.Errorf("preparing ModelMigrationExportTargetAuth insert statement: %w", err)
	}
	stmtDeleteModelMigrationExportTargetAuth, err := sqlair.Prepare(`DELETE FROM "model_migration_export_target_auth"`)
	if err != nil {
		return errors.Errorf("preparing ModelMigrationExportTargetAuth delete statement: %w", err)
	}
	stmtModelMigrationImport, err := sqlair.Prepare(`INSERT INTO "model_migration_import" (*) VALUES ($ModelMigrationImport.*)`, v4_1_0.ModelMigrationImport{})
	if err != nil {
		return errors.Errorf("preparing ModelMigrationImport insert statement: %w", err)
	}
	stmtDeleteModelMigrationImport, err := sqlair.Prepare(`DELETE FROM "model_migration_import"`)
	if err != nil {
		return errors.Errorf("preparing ModelMigrationImport delete statement: %w", err)
	}
	stmtModelMigrationImportExternalControllerModel, err := sqlair.Prepare(`INSERT INTO "model_migration_import_external_controller_model" (*) VALUES ($ModelMigrationImportExternalControllerModel.*)`, v4_1_0.ModelMigrationImportExternalControllerModel{})
	if err != nil {
		return errors.Errorf("preparing ModelMigrationImportExternalControllerModel insert statement: %w", err)
	}
	stmtDeleteModelMigrationImportExternalControllerModel, err := sqlair.Prepare(`DELETE FROM "model_migration_import_external_controller_model"`)
	if err != nil {
		return errors.Errorf("preparing ModelMigrationImportExternalControllerModel delete statement: %w", err)
	}
	stmtModelMigrationImportOffer, err := sqlair.Prepare(`INSERT INTO "model_migration_import_offer" (*) VALUES ($ModelMigrationImportOffer.*)`, v4_1_0.ModelMigrationImportOffer{})
	if err != nil {
		return errors.Errorf("preparing ModelMigrationImportOffer insert statement: %w", err)
	}
	stmtDeleteModelMigrationImportOffer, err := sqlair.Prepare(`DELETE FROM "model_migration_import_offer"`)
	if err != nil {
		return errors.Errorf("preparing ModelMigrationImportOffer delete statement: %w", err)
	}
	stmtModelMigrationImportPhaseType, err := sqlair.Prepare(`INSERT INTO "model_migration_import_phase_type" (*) VALUES ($ModelMigrationImportPhaseType.*) ON CONFLICT DO NOTHING`, v4_1_0.ModelMigrationImportPhaseType{})
	if err != nil {
		return errors.Errorf("preparing ModelMigrationImportPhaseType insert statement: %w", err)
	}
	stmtModelMigrationPhase, err := sqlair.Prepare(`INSERT INTO "model_migration_phase" (*) VALUES ($ModelMigrationPhase.*) ON CONFLICT DO NOTHING`, v4_1_0.ModelMigrationPhase{})
	if err != nil {
		return errors.Errorf("preparing ModelMigrationPhase insert statement: %w", err)
	}
	stmtModelMigrationRedirect, err := sqlair.Prepare(`INSERT INTO "model_migration_redirect" (*) VALUES ($ModelMigrationRedirect.*)`, v4_1_0.ModelMigrationRedirect{})
	if err != nil {
		return errors.Errorf("preparing ModelMigrationRedirect insert statement: %w", err)
	}
	stmtDeleteModelMigrationRedirect, err := sqlair.Prepare(`DELETE FROM "model_migration_redirect"`)
	if err != nil {
		return errors.Errorf("preparing ModelMigrationRedirect delete statement: %w", err)
	}
	stmtModelMigrationRedirectUser, err := sqlair.Prepare(`INSERT INTO "model_migration_redirect_user" (*) VALUES ($ModelMigrationRedirectUser.*)`, v4_1_0.ModelMigrationRedirectUser{})
	if err != nil {
		return errors.Errorf("preparing ModelMigrationRedirectUser insert statement: %w", err)
	}
	stmtDeleteModelMigrationRedirectUser, err := sqlair.Prepare(`DELETE FROM "model_migration_redirect_user"`)
	if err != nil {
		return errors.Errorf("preparing ModelMigrationRedirectUser delete statement: %w", err)
	}
	stmtModelNamespace, err := sqlair.Prepare(`INSERT INTO "model_namespace" (*) VALUES ($ModelNamespace.*)`, v4_1_0.ModelNamespace{})
	if err != nil {
		return errors.Errorf("preparing ModelNamespace insert statement: %w", err)
	}
	stmtDeleteModelNamespace, err := sqlair.Prepare(`DELETE FROM "model_namespace"`)
	if err != nil {
		return errors.Errorf("preparing ModelNamespace delete statement: %w", err)
	}
	stmtModelType, err := sqlair.Prepare(`INSERT INTO "model_type" (*) VALUES ($ModelType.*) ON CONFLICT DO NOTHING`, v4_1_0.ModelType{})
	if err != nil {
		return errors.Errorf("preparing ModelType insert statement: %w", err)
	}
	stmtObjectStoreBackendType, err := sqlair.Prepare(`INSERT INTO "object_store_backend_type" (*) VALUES ($ObjectStoreBackendType.*) ON CONFLICT DO NOTHING`, v4_1_0.ObjectStoreBackendType{})
	if err != nil {
		return errors.Errorf("preparing ObjectStoreBackendType insert statement: %w", err)
	}
	stmtObjectStoreMetadata, err := sqlair.Prepare(`INSERT INTO "object_store_metadata" (*) VALUES ($ObjectStoreMetadata.*)`, v4_1_0.ObjectStoreMetadata{})
	if err != nil {
		return errors.Errorf("preparing ObjectStoreMetadata insert statement: %w", err)
	}
	stmtDeleteObjectStoreMetadata, err := sqlair.Prepare(`DELETE FROM "object_store_metadata"`)
	if err != nil {
		return errors.Errorf("preparing ObjectStoreMetadata delete statement: %w", err)
	}
	stmtObjectStoreMetadataPath, err := sqlair.Prepare(`INSERT INTO "object_store_metadata_path" (*) VALUES ($ObjectStoreMetadataPath.*)`, v4_1_0.ObjectStoreMetadataPath{})
	if err != nil {
		return errors.Errorf("preparing ObjectStoreMetadataPath insert statement: %w", err)
	}
	stmtDeleteObjectStoreMetadataPath, err := sqlair.Prepare(`DELETE FROM "object_store_metadata_path"`)
	if err != nil {
		return errors.Errorf("preparing ObjectStoreMetadataPath delete statement: %w", err)
	}
	stmtPasswordHashAlgorithm, err := sqlair.Prepare(`INSERT INTO "password_hash_algorithm" (*) VALUES ($PasswordHashAlgorithm.*) ON CONFLICT DO NOTHING`, v4_1_0.PasswordHashAlgorithm{})
	if err != nil {
		return errors.Errorf("preparing PasswordHashAlgorithm insert statement: %w", err)
	}
	stmtPermission, err := sqlair.Prepare(`INSERT INTO "permission" (*) VALUES ($Permission.*)`, v4_1_0.Permission{})
	if err != nil {
		return errors.Errorf("preparing Permission insert statement: %w", err)
	}
	stmtDeletePermission, err := sqlair.Prepare(`DELETE FROM "permission"`)
	if err != nil {
		return errors.Errorf("preparing Permission delete statement: %w", err)
	}
	stmtPermissionAccessType, err := sqlair.Prepare(`INSERT INTO "permission_access_type" (*) VALUES ($PermissionAccessType.*) ON CONFLICT DO NOTHING`, v4_1_0.PermissionAccessType{})
	if err != nil {
		return errors.Errorf("preparing PermissionAccessType insert statement: %w", err)
	}
	stmtPermissionObjectAccess, err := sqlair.Prepare(`INSERT INTO "permission_object_access" (*) VALUES ($PermissionObjectAccess.*) ON CONFLICT DO NOTHING`, v4_1_0.PermissionObjectAccess{})
	if err != nil {
		return errors.Errorf("preparing PermissionObjectAccess insert statement: %w", err)
	}
	stmtPermissionObjectType, err := sqlair.Prepare(`INSERT INTO "permission_object_type" (*) VALUES ($PermissionObjectType.*) ON CONFLICT DO NOTHING`, v4_1_0.PermissionObjectType{})
	if err != nil {
		return errors.Errorf("preparing PermissionObjectType insert statement: %w", err)
	}
	stmtSecretBackendOrigin, err := sqlair.Prepare(`INSERT INTO "secret_backend_origin" (*) VALUES ($SecretBackendOrigin.*) ON CONFLICT DO NOTHING`, v4_1_0.SecretBackendOrigin{})
	if err != nil {
		return errors.Errorf("preparing SecretBackendOrigin insert statement: %w", err)
	}
	stmtSecretBackendType, err := sqlair.Prepare(`INSERT INTO "secret_backend_type" (*) VALUES ($SecretBackendType.*) ON CONFLICT DO NOTHING`, v4_1_0.SecretBackendType{})
	if err != nil {
		return errors.Errorf("preparing SecretBackendType insert statement: %w", err)
	}
	stmtSshFingerprintHashAlgorithm, err := sqlair.Prepare(`INSERT INTO "ssh_fingerprint_hash_algorithm" (*) VALUES ($SshFingerprintHashAlgorithm.*) ON CONFLICT DO NOTHING`, v4_1_0.SshFingerprintHashAlgorithm{})
	if err != nil {
		return errors.Errorf("preparing SshFingerprintHashAlgorithm insert statement: %w", err)
	}
	stmtSshKeyAlgorithmType, err := sqlair.Prepare(`INSERT INTO "ssh_key_algorithm_type" (*) VALUES ($SshKeyAlgorithmType.*) ON CONFLICT DO NOTHING`, v4_1_0.SshKeyAlgorithmType{})
	if err != nil {
		return errors.Errorf("preparing SshKeyAlgorithmType insert statement: %w", err)
	}
	stmtUpgradeInfo, err := sqlair.Prepare(`INSERT INTO "upgrade_info" (*) VALUES ($UpgradeInfo.*)`, v4_1_0.UpgradeInfo{})
	if err != nil {
		return errors.Errorf("preparing UpgradeInfo insert statement: %w", err)
	}
	stmtDeleteUpgradeInfo, err := sqlair.Prepare(`DELETE FROM "upgrade_info"`)
	if err != nil {
		return errors.Errorf("preparing UpgradeInfo delete statement: %w", err)
	}
	stmtUpgradeInfoControllerNode, err := sqlair.Prepare(`INSERT INTO "upgrade_info_controller_node" (*) VALUES ($UpgradeInfoControllerNode.*)`, v4_1_0.UpgradeInfoControllerNode{})
	if err != nil {
		return errors.Errorf("preparing UpgradeInfoControllerNode insert statement: %w", err)
	}
	stmtDeleteUpgradeInfoControllerNode, err := sqlair.Prepare(`DELETE FROM "upgrade_info_controller_node"`)
	if err != nil {
		return errors.Errorf("preparing UpgradeInfoControllerNode delete statement: %w", err)
	}
	stmtUpgradeStateType, err := sqlair.Prepare(`INSERT INTO "upgrade_state_type" (*) VALUES ($UpgradeStateType.*) ON CONFLICT DO NOTHING`, v4_1_0.UpgradeStateType{})
	if err != nil {
		return errors.Errorf("preparing UpgradeStateType insert statement: %w", err)
	}
	stmtUser, err := sqlair.Prepare(`INSERT INTO "user" (*) VALUES ($User.*)`, v4_1_0.User{})
	if err != nil {
		return errors.Errorf("preparing User insert statement: %w", err)
	}
	stmtDeleteUser, err := sqlair.Prepare(`DELETE FROM "user"`)
	if err != nil {
		return errors.Errorf("preparing User delete statement: %w", err)
	}
	stmtUserActivationKey, err := sqlair.Prepare(`INSERT INTO "user_activation_key" (*) VALUES ($UserActivationKey.*)`, v4_1_0.UserActivationKey{})
	if err != nil {
		return errors.Errorf("preparing UserActivationKey insert statement: %w", err)
	}
	stmtDeleteUserActivationKey, err := sqlair.Prepare(`DELETE FROM "user_activation_key"`)
	if err != nil {
		return errors.Errorf("preparing UserActivationKey delete statement: %w", err)
	}
	stmtUserAuthentication, err := sqlair.Prepare(`INSERT INTO "user_authentication" (*) VALUES ($UserAuthentication.*)`, v4_1_0.UserAuthentication{})
	if err != nil {
		return errors.Errorf("preparing UserAuthentication insert statement: %w", err)
	}
	stmtDeleteUserAuthentication, err := sqlair.Prepare(`DELETE FROM "user_authentication"`)
	if err != nil {
		return errors.Errorf("preparing UserAuthentication delete statement: %w", err)
	}
	stmtUserPassword, err := sqlair.Prepare(`INSERT INTO "user_password" (*) VALUES ($UserPassword.*)`, v4_1_0.UserPassword{})
	if err != nil {
		return errors.Errorf("preparing UserPassword insert statement: %w", err)
	}
	stmtDeleteUserPassword, err := sqlair.Prepare(`DELETE FROM "user_password"`)
	if err != nil {
		return errors.Errorf("preparing UserPassword delete statement: %w", err)
	}
	stmtUserPublicSshKey, err := sqlair.Prepare(`INSERT INTO "user_public_ssh_key" (*) VALUES ($UserPublicSshKey.*)`, v4_1_0.UserPublicSshKey{})
	if err != nil {
		return errors.Errorf("preparing UserPublicSshKey insert statement: %w", err)
	}
	stmtDeleteUserPublicSshKey, err := sqlair.Prepare(`DELETE FROM "user_public_ssh_key"`)
	if err != nil {
		return errors.Errorf("preparing UserPublicSshKey delete statement: %w", err)
	}
	stmtWorkloadTracingConfig, err := sqlair.Prepare(`INSERT INTO "workload_tracing_config" (*) VALUES ($WorkloadTracingConfig.*)`, v4_1_0.WorkloadTracingConfig{})
	if err != nil {
		return errors.Errorf("preparing WorkloadTracingConfig insert statement: %w", err)
	}
	stmtDeleteWorkloadTracingConfig, err := sqlair.Prepare(`DELETE FROM "workload_tracing_config"`)
	if err != nil {
		return errors.Errorf("preparing WorkloadTracingConfig delete statement: %w", err)
	}

	// Foreign key checks are deferred to commit so the inserts need no
	// topological ordering and self-referential rows within a table are
	// accepted; the constraints are still validated atomically at commit.
	deferFKStmt, err := sqlair.Prepare(`PRAGMA defer_foreign_keys = 1`)
	if err != nil {
		return errors.Errorf("preparing defer foreign keys statement: %w", err)
	}

	db, err := st.DB(ctx)
	if err != nil {
		return errors.Errorf("getting db: %w", err)
	}

	if err := db.Txn(ctx, func(ctx context.Context, tx *sqlair.TX) error {
		if err := tx.Query(ctx, deferFKStmt).Run(); err != nil {
			return errors.Errorf("deferring foreign keys: %w", err)
		}
		// Wipe content tables before the bulk insert: the source logical
		// state wins over the target's bootstrap rows.
		if err := tx.Query(ctx, stmtDeleteAgentBinaryStore).Run(); err != nil {
			return errors.Errorf("wiping AgentBinaryStore (table agent_binary_store): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteAutocertCache).Run(); err != nil {
			return errors.Errorf("wiping AutocertCache (table autocert_cache): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteBakeryConfig).Run(); err != nil {
			return errors.Errorf("wiping BakeryConfig (table bakery_config): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteCharmTracingConfig).Run(); err != nil {
			return errors.Errorf("wiping CharmTracingConfig (table charm_tracing_config): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteCloud).Run(); err != nil {
			return errors.Errorf("wiping Cloud (table cloud): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteCloudAuthType).Run(); err != nil {
			return errors.Errorf("wiping CloudAuthType (table cloud_auth_type): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteCloudCaCert).Run(); err != nil {
			return errors.Errorf("wiping CloudCaCert (table cloud_ca_cert): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteCloudCredential).Run(); err != nil {
			return errors.Errorf("wiping CloudCredential (table cloud_credential): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteCloudCredentialAttribute).Run(); err != nil {
			return errors.Errorf("wiping CloudCredentialAttribute (table cloud_credential_attribute): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteCloudDefaults).Run(); err != nil {
			return errors.Errorf("wiping CloudDefaults (table cloud_defaults): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteCloudImageMetadata).Run(); err != nil {
			return errors.Errorf("wiping CloudImageMetadata (table cloud_image_metadata): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteCloudRegion).Run(); err != nil {
			return errors.Errorf("wiping CloudRegion (table cloud_region): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteCloudRegionDefaults).Run(); err != nil {
			return errors.Errorf("wiping CloudRegionDefaults (table cloud_region_defaults): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteExternalController).Run(); err != nil {
			return errors.Errorf("wiping ExternalController (table external_controller): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteExternalControllerAddress).Run(); err != nil {
			return errors.Errorf("wiping ExternalControllerAddress (table external_controller_address): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteExternalModel).Run(); err != nil {
			return errors.Errorf("wiping ExternalModel (table external_model): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteFlag).Run(); err != nil {
			return errors.Errorf("wiping Flag (table flag): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteLease).Run(); err != nil {
			return errors.Errorf("wiping Lease (table lease): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteLeasePin).Run(); err != nil {
			return errors.Errorf("wiping LeasePin (table lease_pin): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteLoggingLokiConfig).Run(); err != nil {
			return errors.Errorf("wiping LoggingLokiConfig (table logging_loki_config): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteMacaroonRootKey).Run(); err != nil {
			return errors.Errorf("wiping MacaroonRootKey (table macaroon_root_key): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteModel).Run(); err != nil {
			return errors.Errorf("wiping Model (table model): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteModelAuthorizedKeys).Run(); err != nil {
			return errors.Errorf("wiping ModelAuthorizedKeys (table model_authorized_keys): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteModelDatabaseDeletion).Run(); err != nil {
			return errors.Errorf("wiping ModelDatabaseDeletion (table model_database_deletion): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteModelLastLogin).Run(); err != nil {
			return errors.Errorf("wiping ModelLastLogin (table model_last_login): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteModelMigrationExport).Run(); err != nil {
			return errors.Errorf("wiping ModelMigrationExport (table model_migration_export): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteModelMigrationExportMinionSync).Run(); err != nil {
			return errors.Errorf("wiping ModelMigrationExportMinionSync (table model_migration_export_minion_sync): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteModelMigrationExportOffer).Run(); err != nil {
			return errors.Errorf("wiping ModelMigrationExportOffer (table model_migration_export_offer): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteModelMigrationExportPhase).Run(); err != nil {
			return errors.Errorf("wiping ModelMigrationExportPhase (table model_migration_export_phase): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteModelMigrationExportStatus).Run(); err != nil {
			return errors.Errorf("wiping ModelMigrationExportStatus (table model_migration_export_status): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteModelMigrationExportTargetAuth).Run(); err != nil {
			return errors.Errorf("wiping ModelMigrationExportTargetAuth (table model_migration_export_target_auth): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteModelMigrationImport).Run(); err != nil {
			return errors.Errorf("wiping ModelMigrationImport (table model_migration_import): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteModelMigrationImportExternalControllerModel).Run(); err != nil {
			return errors.Errorf("wiping ModelMigrationImportExternalControllerModel (table model_migration_import_external_controller_model): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteModelMigrationImportOffer).Run(); err != nil {
			return errors.Errorf("wiping ModelMigrationImportOffer (table model_migration_import_offer): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteModelMigrationRedirect).Run(); err != nil {
			return errors.Errorf("wiping ModelMigrationRedirect (table model_migration_redirect): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteModelMigrationRedirectUser).Run(); err != nil {
			return errors.Errorf("wiping ModelMigrationRedirectUser (table model_migration_redirect_user): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteModelNamespace).Run(); err != nil {
			return errors.Errorf("wiping ModelNamespace (table model_namespace): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteObjectStoreMetadata).Run(); err != nil {
			return errors.Errorf("wiping ObjectStoreMetadata (table object_store_metadata): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteObjectStoreMetadataPath).Run(); err != nil {
			return errors.Errorf("wiping ObjectStoreMetadataPath (table object_store_metadata_path): %w", err)
		}
		if err := tx.Query(ctx, stmtDeletePermission).Run(); err != nil {
			return errors.Errorf("wiping Permission (table permission): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteUpgradeInfo).Run(); err != nil {
			return errors.Errorf("wiping UpgradeInfo (table upgrade_info): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteUpgradeInfoControllerNode).Run(); err != nil {
			return errors.Errorf("wiping UpgradeInfoControllerNode (table upgrade_info_controller_node): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteUser).Run(); err != nil {
			return errors.Errorf("wiping User (table user): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteUserActivationKey).Run(); err != nil {
			return errors.Errorf("wiping UserActivationKey (table user_activation_key): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteUserAuthentication).Run(); err != nil {
			return errors.Errorf("wiping UserAuthentication (table user_authentication): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteUserPassword).Run(); err != nil {
			return errors.Errorf("wiping UserPassword (table user_password): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteUserPublicSshKey).Run(); err != nil {
			return errors.Errorf("wiping UserPublicSshKey (table user_public_ssh_key): %w", err)
		}
		if err := tx.Query(ctx, stmtDeleteWorkloadTracingConfig).Run(); err != nil {
			return errors.Errorf("wiping WorkloadTracingConfig (table workload_tracing_config): %w", err)
		}
		if len(p.AgentBinaryStore) > 0 {
			if err := tx.Query(ctx, stmtAgentBinaryStore, p.AgentBinaryStore).Run(); err != nil {
				return errors.Errorf("inserting AgentBinaryStore (table agent_binary_store): %w", err)
			}
		}
		if len(p.Architecture) > 0 {
			if err := tx.Query(ctx, stmtArchitecture, p.Architecture).Run(); err != nil {
				return errors.Errorf("inserting Architecture (table architecture): %w", err)
			}
		}
		if len(p.AuthType) > 0 {
			if err := tx.Query(ctx, stmtAuthType, p.AuthType).Run(); err != nil {
				return errors.Errorf("inserting AuthType (table auth_type): %w", err)
			}
		}
		if len(p.AutocertCache) > 0 {
			if err := tx.Query(ctx, stmtAutocertCache, p.AutocertCache).Run(); err != nil {
				return errors.Errorf("inserting AutocertCache (table autocert_cache): %w", err)
			}
		}
		if len(p.AutocertCacheEncoding) > 0 {
			if err := tx.Query(ctx, stmtAutocertCacheEncoding, p.AutocertCacheEncoding).Run(); err != nil {
				return errors.Errorf("inserting AutocertCacheEncoding (table autocert_cache_encoding): %w", err)
			}
		}
		if len(p.BakeryConfig) > 0 {
			if err := tx.Query(ctx, stmtBakeryConfig, p.BakeryConfig).Run(); err != nil {
				return errors.Errorf("inserting BakeryConfig (table bakery_config): %w", err)
			}
		}
		if len(p.CharmTracingConfig) > 0 {
			if err := tx.Query(ctx, stmtCharmTracingConfig, p.CharmTracingConfig).Run(); err != nil {
				return errors.Errorf("inserting CharmTracingConfig (table charm_tracing_config): %w", err)
			}
		}
		if len(p.Cloud) > 0 {
			if err := tx.Query(ctx, stmtCloud, p.Cloud).Run(); err != nil {
				return errors.Errorf("inserting Cloud (table cloud): %w", err)
			}
		}
		if len(p.CloudAuthType) > 0 {
			if err := tx.Query(ctx, stmtCloudAuthType, p.CloudAuthType).Run(); err != nil {
				return errors.Errorf("inserting CloudAuthType (table cloud_auth_type): %w", err)
			}
		}
		if len(p.CloudCaCert) > 0 {
			if err := tx.Query(ctx, stmtCloudCaCert, p.CloudCaCert).Run(); err != nil {
				return errors.Errorf("inserting CloudCaCert (table cloud_ca_cert): %w", err)
			}
		}
		if len(p.CloudCredential) > 0 {
			if err := tx.Query(ctx, stmtCloudCredential, p.CloudCredential).Run(); err != nil {
				return errors.Errorf("inserting CloudCredential (table cloud_credential): %w", err)
			}
		}
		if len(p.CloudCredentialAttribute) > 0 {
			if err := tx.Query(ctx, stmtCloudCredentialAttribute, p.CloudCredentialAttribute).Run(); err != nil {
				return errors.Errorf("inserting CloudCredentialAttribute (table cloud_credential_attribute): %w", err)
			}
		}
		if len(p.CloudDefaults) > 0 {
			if err := tx.Query(ctx, stmtCloudDefaults, p.CloudDefaults).Run(); err != nil {
				return errors.Errorf("inserting CloudDefaults (table cloud_defaults): %w", err)
			}
		}
		if len(p.CloudImageMetadata) > 0 {
			if err := tx.Query(ctx, stmtCloudImageMetadata, p.CloudImageMetadata).Run(); err != nil {
				return errors.Errorf("inserting CloudImageMetadata (table cloud_image_metadata): %w", err)
			}
		}
		if len(p.CloudRegion) > 0 {
			if err := tx.Query(ctx, stmtCloudRegion, p.CloudRegion).Run(); err != nil {
				return errors.Errorf("inserting CloudRegion (table cloud_region): %w", err)
			}
		}
		if len(p.CloudRegionDefaults) > 0 {
			if err := tx.Query(ctx, stmtCloudRegionDefaults, p.CloudRegionDefaults).Run(); err != nil {
				return errors.Errorf("inserting CloudRegionDefaults (table cloud_region_defaults): %w", err)
			}
		}
		if len(p.CloudType) > 0 {
			if err := tx.Query(ctx, stmtCloudType, p.CloudType).Run(); err != nil {
				return errors.Errorf("inserting CloudType (table cloud_type): %w", err)
			}
		}
		if len(p.ExternalController) > 0 {
			if err := tx.Query(ctx, stmtExternalController, p.ExternalController).Run(); err != nil {
				return errors.Errorf("inserting ExternalController (table external_controller): %w", err)
			}
		}
		if len(p.ExternalControllerAddress) > 0 {
			if err := tx.Query(ctx, stmtExternalControllerAddress, p.ExternalControllerAddress).Run(); err != nil {
				return errors.Errorf("inserting ExternalControllerAddress (table external_controller_address): %w", err)
			}
		}
		if len(p.ExternalModel) > 0 {
			if err := tx.Query(ctx, stmtExternalModel, p.ExternalModel).Run(); err != nil {
				return errors.Errorf("inserting ExternalModel (table external_model): %w", err)
			}
		}
		if len(p.Flag) > 0 {
			if err := tx.Query(ctx, stmtFlag, p.Flag).Run(); err != nil {
				return errors.Errorf("inserting Flag (table flag): %w", err)
			}
		}
		if len(p.Lease) > 0 {
			if err := tx.Query(ctx, stmtLease, p.Lease).Run(); err != nil {
				return errors.Errorf("inserting Lease (table lease): %w", err)
			}
		}
		if len(p.LeasePin) > 0 {
			if err := tx.Query(ctx, stmtLeasePin, p.LeasePin).Run(); err != nil {
				return errors.Errorf("inserting LeasePin (table lease_pin): %w", err)
			}
		}
		if len(p.LeaseType) > 0 {
			if err := tx.Query(ctx, stmtLeaseType, p.LeaseType).Run(); err != nil {
				return errors.Errorf("inserting LeaseType (table lease_type): %w", err)
			}
		}
		if len(p.Life) > 0 {
			if err := tx.Query(ctx, stmtLife, p.Life).Run(); err != nil {
				return errors.Errorf("inserting Life (table life): %w", err)
			}
		}
		if len(p.LoggingLokiConfig) > 0 {
			if err := tx.Query(ctx, stmtLoggingLokiConfig, p.LoggingLokiConfig).Run(); err != nil {
				return errors.Errorf("inserting LoggingLokiConfig (table logging_loki_config): %w", err)
			}
		}
		if len(p.MacaroonRootKey) > 0 {
			if err := tx.Query(ctx, stmtMacaroonRootKey, p.MacaroonRootKey).Run(); err != nil {
				return errors.Errorf("inserting MacaroonRootKey (table macaroon_root_key): %w", err)
			}
		}
		if len(p.Model) > 0 {
			if err := tx.Query(ctx, stmtModel, p.Model).Run(); err != nil {
				return errors.Errorf("inserting Model (table model): %w", err)
			}
		}
		if len(p.ModelAuthorizedKeys) > 0 {
			if err := tx.Query(ctx, stmtModelAuthorizedKeys, p.ModelAuthorizedKeys).Run(); err != nil {
				return errors.Errorf("inserting ModelAuthorizedKeys (table model_authorized_keys): %w", err)
			}
		}
		if len(p.ModelDatabaseDeletion) > 0 {
			if err := tx.Query(ctx, stmtModelDatabaseDeletion, p.ModelDatabaseDeletion).Run(); err != nil {
				return errors.Errorf("inserting ModelDatabaseDeletion (table model_database_deletion): %w", err)
			}
		}
		if len(p.ModelLastLogin) > 0 {
			if err := tx.Query(ctx, stmtModelLastLogin, p.ModelLastLogin).Run(); err != nil {
				return errors.Errorf("inserting ModelLastLogin (table model_last_login): %w", err)
			}
		}
		if len(p.ModelMigrationExport) > 0 {
			if err := tx.Query(ctx, stmtModelMigrationExport, p.ModelMigrationExport).Run(); err != nil {
				return errors.Errorf("inserting ModelMigrationExport (table model_migration_export): %w", err)
			}
		}
		if len(p.ModelMigrationExportMinionSync) > 0 {
			if err := tx.Query(ctx, stmtModelMigrationExportMinionSync, p.ModelMigrationExportMinionSync).Run(); err != nil {
				return errors.Errorf("inserting ModelMigrationExportMinionSync (table model_migration_export_minion_sync): %w", err)
			}
		}
		if len(p.ModelMigrationExportOffer) > 0 {
			if err := tx.Query(ctx, stmtModelMigrationExportOffer, p.ModelMigrationExportOffer).Run(); err != nil {
				return errors.Errorf("inserting ModelMigrationExportOffer (table model_migration_export_offer): %w", err)
			}
		}
		if len(p.ModelMigrationExportPhase) > 0 {
			if err := tx.Query(ctx, stmtModelMigrationExportPhase, p.ModelMigrationExportPhase).Run(); err != nil {
				return errors.Errorf("inserting ModelMigrationExportPhase (table model_migration_export_phase): %w", err)
			}
		}
		if len(p.ModelMigrationExportStatus) > 0 {
			if err := tx.Query(ctx, stmtModelMigrationExportStatus, p.ModelMigrationExportStatus).Run(); err != nil {
				return errors.Errorf("inserting ModelMigrationExportStatus (table model_migration_export_status): %w", err)
			}
		}
		if len(p.ModelMigrationExportTargetAuth) > 0 {
			if err := tx.Query(ctx, stmtModelMigrationExportTargetAuth, p.ModelMigrationExportTargetAuth).Run(); err != nil {
				return errors.Errorf("inserting ModelMigrationExportTargetAuth (table model_migration_export_target_auth): %w", err)
			}
		}
		if len(p.ModelMigrationImport) > 0 {
			if err := tx.Query(ctx, stmtModelMigrationImport, p.ModelMigrationImport).Run(); err != nil {
				return errors.Errorf("inserting ModelMigrationImport (table model_migration_import): %w", err)
			}
		}
		if len(p.ModelMigrationImportExternalControllerModel) > 0 {
			if err := tx.Query(ctx, stmtModelMigrationImportExternalControllerModel, p.ModelMigrationImportExternalControllerModel).Run(); err != nil {
				return errors.Errorf("inserting ModelMigrationImportExternalControllerModel (table model_migration_import_external_controller_model): %w", err)
			}
		}
		if len(p.ModelMigrationImportOffer) > 0 {
			if err := tx.Query(ctx, stmtModelMigrationImportOffer, p.ModelMigrationImportOffer).Run(); err != nil {
				return errors.Errorf("inserting ModelMigrationImportOffer (table model_migration_import_offer): %w", err)
			}
		}
		if len(p.ModelMigrationImportPhaseType) > 0 {
			if err := tx.Query(ctx, stmtModelMigrationImportPhaseType, p.ModelMigrationImportPhaseType).Run(); err != nil {
				return errors.Errorf("inserting ModelMigrationImportPhaseType (table model_migration_import_phase_type): %w", err)
			}
		}
		if len(p.ModelMigrationPhase) > 0 {
			if err := tx.Query(ctx, stmtModelMigrationPhase, p.ModelMigrationPhase).Run(); err != nil {
				return errors.Errorf("inserting ModelMigrationPhase (table model_migration_phase): %w", err)
			}
		}
		if len(p.ModelMigrationRedirect) > 0 {
			if err := tx.Query(ctx, stmtModelMigrationRedirect, p.ModelMigrationRedirect).Run(); err != nil {
				return errors.Errorf("inserting ModelMigrationRedirect (table model_migration_redirect): %w", err)
			}
		}
		if len(p.ModelMigrationRedirectUser) > 0 {
			if err := tx.Query(ctx, stmtModelMigrationRedirectUser, p.ModelMigrationRedirectUser).Run(); err != nil {
				return errors.Errorf("inserting ModelMigrationRedirectUser (table model_migration_redirect_user): %w", err)
			}
		}
		if len(p.ModelNamespace) > 0 {
			if err := tx.Query(ctx, stmtModelNamespace, p.ModelNamespace).Run(); err != nil {
				return errors.Errorf("inserting ModelNamespace (table model_namespace): %w", err)
			}
		}
		if len(p.ModelType) > 0 {
			if err := tx.Query(ctx, stmtModelType, p.ModelType).Run(); err != nil {
				return errors.Errorf("inserting ModelType (table model_type): %w", err)
			}
		}
		if len(p.ObjectStoreBackendType) > 0 {
			if err := tx.Query(ctx, stmtObjectStoreBackendType, p.ObjectStoreBackendType).Run(); err != nil {
				return errors.Errorf("inserting ObjectStoreBackendType (table object_store_backend_type): %w", err)
			}
		}
		if len(p.ObjectStoreMetadata) > 0 {
			if err := tx.Query(ctx, stmtObjectStoreMetadata, p.ObjectStoreMetadata).Run(); err != nil {
				return errors.Errorf("inserting ObjectStoreMetadata (table object_store_metadata): %w", err)
			}
		}
		if len(p.ObjectStoreMetadataPath) > 0 {
			if err := tx.Query(ctx, stmtObjectStoreMetadataPath, p.ObjectStoreMetadataPath).Run(); err != nil {
				return errors.Errorf("inserting ObjectStoreMetadataPath (table object_store_metadata_path): %w", err)
			}
		}
		if len(p.PasswordHashAlgorithm) > 0 {
			if err := tx.Query(ctx, stmtPasswordHashAlgorithm, p.PasswordHashAlgorithm).Run(); err != nil {
				return errors.Errorf("inserting PasswordHashAlgorithm (table password_hash_algorithm): %w", err)
			}
		}
		if len(p.Permission) > 0 {
			if err := tx.Query(ctx, stmtPermission, p.Permission).Run(); err != nil {
				return errors.Errorf("inserting Permission (table permission): %w", err)
			}
		}
		if len(p.PermissionAccessType) > 0 {
			if err := tx.Query(ctx, stmtPermissionAccessType, p.PermissionAccessType).Run(); err != nil {
				return errors.Errorf("inserting PermissionAccessType (table permission_access_type): %w", err)
			}
		}
		if len(p.PermissionObjectAccess) > 0 {
			if err := tx.Query(ctx, stmtPermissionObjectAccess, p.PermissionObjectAccess).Run(); err != nil {
				return errors.Errorf("inserting PermissionObjectAccess (table permission_object_access): %w", err)
			}
		}
		if len(p.PermissionObjectType) > 0 {
			if err := tx.Query(ctx, stmtPermissionObjectType, p.PermissionObjectType).Run(); err != nil {
				return errors.Errorf("inserting PermissionObjectType (table permission_object_type): %w", err)
			}
		}
		if len(p.SecretBackendOrigin) > 0 {
			if err := tx.Query(ctx, stmtSecretBackendOrigin, p.SecretBackendOrigin).Run(); err != nil {
				return errors.Errorf("inserting SecretBackendOrigin (table secret_backend_origin): %w", err)
			}
		}
		if len(p.SecretBackendType) > 0 {
			if err := tx.Query(ctx, stmtSecretBackendType, p.SecretBackendType).Run(); err != nil {
				return errors.Errorf("inserting SecretBackendType (table secret_backend_type): %w", err)
			}
		}
		if len(p.SshFingerprintHashAlgorithm) > 0 {
			if err := tx.Query(ctx, stmtSshFingerprintHashAlgorithm, p.SshFingerprintHashAlgorithm).Run(); err != nil {
				return errors.Errorf("inserting SshFingerprintHashAlgorithm (table ssh_fingerprint_hash_algorithm): %w", err)
			}
		}
		if len(p.SshKeyAlgorithmType) > 0 {
			if err := tx.Query(ctx, stmtSshKeyAlgorithmType, p.SshKeyAlgorithmType).Run(); err != nil {
				return errors.Errorf("inserting SshKeyAlgorithmType (table ssh_key_algorithm_type): %w", err)
			}
		}
		if len(p.UpgradeInfo) > 0 {
			if err := tx.Query(ctx, stmtUpgradeInfo, p.UpgradeInfo).Run(); err != nil {
				return errors.Errorf("inserting UpgradeInfo (table upgrade_info): %w", err)
			}
		}
		if len(p.UpgradeInfoControllerNode) > 0 {
			if err := tx.Query(ctx, stmtUpgradeInfoControllerNode, p.UpgradeInfoControllerNode).Run(); err != nil {
				return errors.Errorf("inserting UpgradeInfoControllerNode (table upgrade_info_controller_node): %w", err)
			}
		}
		if len(p.UpgradeStateType) > 0 {
			if err := tx.Query(ctx, stmtUpgradeStateType, p.UpgradeStateType).Run(); err != nil {
				return errors.Errorf("inserting UpgradeStateType (table upgrade_state_type): %w", err)
			}
		}
		if len(p.User) > 0 {
			if err := tx.Query(ctx, stmtUser, p.User).Run(); err != nil {
				return errors.Errorf("inserting User (table user): %w", err)
			}
		}
		if len(p.UserActivationKey) > 0 {
			if err := tx.Query(ctx, stmtUserActivationKey, p.UserActivationKey).Run(); err != nil {
				return errors.Errorf("inserting UserActivationKey (table user_activation_key): %w", err)
			}
		}
		if len(p.UserAuthentication) > 0 {
			if err := tx.Query(ctx, stmtUserAuthentication, p.UserAuthentication).Run(); err != nil {
				return errors.Errorf("inserting UserAuthentication (table user_authentication): %w", err)
			}
		}
		if len(p.UserPassword) > 0 {
			if err := tx.Query(ctx, stmtUserPassword, p.UserPassword).Run(); err != nil {
				return errors.Errorf("inserting UserPassword (table user_password): %w", err)
			}
		}
		if len(p.UserPublicSshKey) > 0 {
			if err := tx.Query(ctx, stmtUserPublicSshKey, p.UserPublicSshKey).Run(); err != nil {
				return errors.Errorf("inserting UserPublicSshKey (table user_public_ssh_key): %w", err)
			}
		}
		if len(p.WorkloadTracingConfig) > 0 {
			if err := tx.Query(ctx, stmtWorkloadTracingConfig, p.WorkloadTracingConfig).Run(); err != nil {
				return errors.Errorf("inserting WorkloadTracingConfig (table workload_tracing_config): %w", err)
			}
		}
		return nil
	}); err != nil {
		return errors.Errorf("importing controller data: %w", err)
	}

	return nil
}
