// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/domain/crossmodelrelation/service (interfaces: ControllerState,ModelState,ModelMigrationState,ModelRemoteApplicationState,WatcherFactory)
//
// Generated by this command:
//
//	mockgen -typed -package service -destination package_mock_test.go github.com/juju/juju/domain/crossmodelrelation/service ControllerState,ModelState,ModelMigrationState,ModelRemoteApplicationState,WatcherFactory
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	user "github.com/juju/juju/core/user"
	watcher "github.com/juju/juju/core/watcher"
	eventsource "github.com/juju/juju/core/watcher/eventsource"
	crossmodelrelation "github.com/juju/juju/domain/crossmodelrelation"
	internal "github.com/juju/juju/domain/crossmodelrelation/internal"
	uuid "github.com/juju/juju/internal/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockControllerState is a mock of ControllerState interface.
type MockControllerState struct {
	ctrl     *gomock.Controller
	recorder *MockControllerStateMockRecorder
}

// MockControllerStateMockRecorder is the mock recorder for MockControllerState.
type MockControllerStateMockRecorder struct {
	mock *MockControllerState
}

// NewMockControllerState creates a new mock instance.
func NewMockControllerState(ctrl *gomock.Controller) *MockControllerState {
	mock := &MockControllerState{ctrl: ctrl}
	mock.recorder = &MockControllerStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockControllerState) EXPECT() *MockControllerStateMockRecorder {
	return m.recorder
}

// CreateOfferAccess mocks base method.
func (m *MockControllerState) CreateOfferAccess(arg0 context.Context, arg1, arg2, arg3 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOfferAccess", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOfferAccess indicates an expected call of CreateOfferAccess.
func (mr *MockControllerStateMockRecorder) CreateOfferAccess(arg0, arg1, arg2, arg3 any) *MockControllerStateCreateOfferAccessCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOfferAccess", reflect.TypeOf((*MockControllerState)(nil).CreateOfferAccess), arg0, arg1, arg2, arg3)
	return &MockControllerStateCreateOfferAccessCall{Call: call}
}

// MockControllerStateCreateOfferAccessCall wrap *gomock.Call
type MockControllerStateCreateOfferAccessCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerStateCreateOfferAccessCall) Return(arg0 error) *MockControllerStateCreateOfferAccessCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerStateCreateOfferAccessCall) Do(f func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) *MockControllerStateCreateOfferAccessCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerStateCreateOfferAccessCall) DoAndReturn(f func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) *MockControllerStateCreateOfferAccessCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetOfferUUIDsForUsersWithConsume mocks base method.
func (m *MockControllerState) GetOfferUUIDsForUsersWithConsume(arg0 context.Context, arg1 []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOfferUUIDsForUsersWithConsume", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOfferUUIDsForUsersWithConsume indicates an expected call of GetOfferUUIDsForUsersWithConsume.
func (mr *MockControllerStateMockRecorder) GetOfferUUIDsForUsersWithConsume(arg0, arg1 any) *MockControllerStateGetOfferUUIDsForUsersWithConsumeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOfferUUIDsForUsersWithConsume", reflect.TypeOf((*MockControllerState)(nil).GetOfferUUIDsForUsersWithConsume), arg0, arg1)
	return &MockControllerStateGetOfferUUIDsForUsersWithConsumeCall{Call: call}
}

// MockControllerStateGetOfferUUIDsForUsersWithConsumeCall wrap *gomock.Call
type MockControllerStateGetOfferUUIDsForUsersWithConsumeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerStateGetOfferUUIDsForUsersWithConsumeCall) Return(arg0 []string, arg1 error) *MockControllerStateGetOfferUUIDsForUsersWithConsumeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerStateGetOfferUUIDsForUsersWithConsumeCall) Do(f func(context.Context, []string) ([]string, error)) *MockControllerStateGetOfferUUIDsForUsersWithConsumeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerStateGetOfferUUIDsForUsersWithConsumeCall) DoAndReturn(f func(context.Context, []string) ([]string, error)) *MockControllerStateGetOfferUUIDsForUsersWithConsumeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUserUUIDByName mocks base method.
func (m *MockControllerState) GetUserUUIDByName(arg0 context.Context, arg1 user.Name) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserUUIDByName", arg0, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserUUIDByName indicates an expected call of GetUserUUIDByName.
func (mr *MockControllerStateMockRecorder) GetUserUUIDByName(arg0, arg1 any) *MockControllerStateGetUserUUIDByNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserUUIDByName", reflect.TypeOf((*MockControllerState)(nil).GetUserUUIDByName), arg0, arg1)
	return &MockControllerStateGetUserUUIDByNameCall{Call: call}
}

// MockControllerStateGetUserUUIDByNameCall wrap *gomock.Call
type MockControllerStateGetUserUUIDByNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerStateGetUserUUIDByNameCall) Return(arg0 uuid.UUID, arg1 error) *MockControllerStateGetUserUUIDByNameCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerStateGetUserUUIDByNameCall) Do(f func(context.Context, user.Name) (uuid.UUID, error)) *MockControllerStateGetUserUUIDByNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerStateGetUserUUIDByNameCall) DoAndReturn(f func(context.Context, user.Name) (uuid.UUID, error)) *MockControllerStateGetUserUUIDByNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUsersForOfferUUIDs mocks base method.
func (m *MockControllerState) GetUsersForOfferUUIDs(arg0 context.Context, arg1 []string) (map[string][]crossmodelrelation.OfferUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersForOfferUUIDs", arg0, arg1)
	ret0, _ := ret[0].(map[string][]crossmodelrelation.OfferUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersForOfferUUIDs indicates an expected call of GetUsersForOfferUUIDs.
func (mr *MockControllerStateMockRecorder) GetUsersForOfferUUIDs(arg0, arg1 any) *MockControllerStateGetUsersForOfferUUIDsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersForOfferUUIDs", reflect.TypeOf((*MockControllerState)(nil).GetUsersForOfferUUIDs), arg0, arg1)
	return &MockControllerStateGetUsersForOfferUUIDsCall{Call: call}
}

// MockControllerStateGetUsersForOfferUUIDsCall wrap *gomock.Call
type MockControllerStateGetUsersForOfferUUIDsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerStateGetUsersForOfferUUIDsCall) Return(arg0 map[string][]crossmodelrelation.OfferUser, arg1 error) *MockControllerStateGetUsersForOfferUUIDsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerStateGetUsersForOfferUUIDsCall) Do(f func(context.Context, []string) (map[string][]crossmodelrelation.OfferUser, error)) *MockControllerStateGetUsersForOfferUUIDsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerStateGetUsersForOfferUUIDsCall) DoAndReturn(f func(context.Context, []string) (map[string][]crossmodelrelation.OfferUser, error)) *MockControllerStateGetUsersForOfferUUIDsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockModelState is a mock of ModelState interface.
type MockModelState struct {
	ctrl     *gomock.Controller
	recorder *MockModelStateMockRecorder
}

// MockModelStateMockRecorder is the mock recorder for MockModelState.
type MockModelStateMockRecorder struct {
	mock *MockModelState
}

// NewMockModelState creates a new mock instance.
func NewMockModelState(ctrl *gomock.Controller) *MockModelState {
	mock := &MockModelState{ctrl: ctrl}
	mock.recorder = &MockModelStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelState) EXPECT() *MockModelStateMockRecorder {
	return m.recorder
}

// AddRemoteApplicationConsumer mocks base method.
func (m *MockModelState) AddRemoteApplicationConsumer(arg0 context.Context, arg1 string, arg2 crossmodelrelation.AddRemoteApplicationConsumerArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRemoteApplicationConsumer", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRemoteApplicationConsumer indicates an expected call of AddRemoteApplicationConsumer.
func (mr *MockModelStateMockRecorder) AddRemoteApplicationConsumer(arg0, arg1, arg2 any) *MockModelStateAddRemoteApplicationConsumerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRemoteApplicationConsumer", reflect.TypeOf((*MockModelState)(nil).AddRemoteApplicationConsumer), arg0, arg1, arg2)
	return &MockModelStateAddRemoteApplicationConsumerCall{Call: call}
}

// MockModelStateAddRemoteApplicationConsumerCall wrap *gomock.Call
type MockModelStateAddRemoteApplicationConsumerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelStateAddRemoteApplicationConsumerCall) Return(arg0 error) *MockModelStateAddRemoteApplicationConsumerCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelStateAddRemoteApplicationConsumerCall) Do(f func(context.Context, string, crossmodelrelation.AddRemoteApplicationConsumerArgs) error) *MockModelStateAddRemoteApplicationConsumerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelStateAddRemoteApplicationConsumerCall) DoAndReturn(f func(context.Context, string, crossmodelrelation.AddRemoteApplicationConsumerArgs) error) *MockModelStateAddRemoteApplicationConsumerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddRemoteApplicationOfferer mocks base method.
func (m *MockModelState) AddRemoteApplicationOfferer(arg0 context.Context, arg1 string, arg2 crossmodelrelation.AddRemoteApplicationOffererArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRemoteApplicationOfferer", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRemoteApplicationOfferer indicates an expected call of AddRemoteApplicationOfferer.
func (mr *MockModelStateMockRecorder) AddRemoteApplicationOfferer(arg0, arg1, arg2 any) *MockModelStateAddRemoteApplicationOffererCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRemoteApplicationOfferer", reflect.TypeOf((*MockModelState)(nil).AddRemoteApplicationOfferer), arg0, arg1, arg2)
	return &MockModelStateAddRemoteApplicationOffererCall{Call: call}
}

// MockModelStateAddRemoteApplicationOffererCall wrap *gomock.Call
type MockModelStateAddRemoteApplicationOffererCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelStateAddRemoteApplicationOffererCall) Return(arg0 error) *MockModelStateAddRemoteApplicationOffererCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelStateAddRemoteApplicationOffererCall) Do(f func(context.Context, string, crossmodelrelation.AddRemoteApplicationOffererArgs) error) *MockModelStateAddRemoteApplicationOffererCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelStateAddRemoteApplicationOffererCall) DoAndReturn(f func(context.Context, string, crossmodelrelation.AddRemoteApplicationOffererArgs) error) *MockModelStateAddRemoteApplicationOffererCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateOffer mocks base method.
func (m *MockModelState) CreateOffer(arg0 context.Context, arg1 internal.CreateOfferArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOffer", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOffer indicates an expected call of CreateOffer.
func (mr *MockModelStateMockRecorder) CreateOffer(arg0, arg1 any) *MockModelStateCreateOfferCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOffer", reflect.TypeOf((*MockModelState)(nil).CreateOffer), arg0, arg1)
	return &MockModelStateCreateOfferCall{Call: call}
}

// MockModelStateCreateOfferCall wrap *gomock.Call
type MockModelStateCreateOfferCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelStateCreateOfferCall) Return(arg0 error) *MockModelStateCreateOfferCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelStateCreateOfferCall) Do(f func(context.Context, internal.CreateOfferArgs) error) *MockModelStateCreateOfferCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelStateCreateOfferCall) DoAndReturn(f func(context.Context, internal.CreateOfferArgs) error) *MockModelStateCreateOfferCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteFailedOffer mocks base method.
func (m *MockModelState) DeleteFailedOffer(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFailedOffer", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFailedOffer indicates an expected call of DeleteFailedOffer.
func (mr *MockModelStateMockRecorder) DeleteFailedOffer(arg0, arg1 any) *MockModelStateDeleteFailedOfferCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFailedOffer", reflect.TypeOf((*MockModelState)(nil).DeleteFailedOffer), arg0, arg1)
	return &MockModelStateDeleteFailedOfferCall{Call: call}
}

// MockModelStateDeleteFailedOfferCall wrap *gomock.Call
type MockModelStateDeleteFailedOfferCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelStateDeleteFailedOfferCall) Return(arg0 error) *MockModelStateDeleteFailedOfferCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelStateDeleteFailedOfferCall) Do(f func(context.Context, uuid.UUID) error) *MockModelStateDeleteFailedOfferCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelStateDeleteFailedOfferCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockModelStateDeleteFailedOfferCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetConsumedSecretURIsWithChanges mocks base method.
func (m *MockModelState) GetConsumedSecretURIsWithChanges(arg0 context.Context, arg1 string, arg2 ...string) ([]SecretRevisionChange, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetConsumedSecretURIsWithChanges", varargs...)
	ret0, _ := ret[0].([]SecretRevisionChange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConsumedSecretURIsWithChanges indicates an expected call of GetConsumedSecretURIsWithChanges.
func (mr *MockModelStateMockRecorder) GetConsumedSecretURIsWithChanges(arg0, arg1 any, arg2 ...any) *MockModelStateGetConsumedSecretURIsWithChangesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsumedSecretURIsWithChanges", reflect.TypeOf((*MockModelState)(nil).GetConsumedSecretURIsWithChanges), varargs...)
	return &MockModelStateGetConsumedSecretURIsWithChangesCall{Call: call}
}

// MockModelStateGetConsumedSecretURIsWithChangesCall wrap *gomock.Call
type MockModelStateGetConsumedSecretURIsWithChangesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelStateGetConsumedSecretURIsWithChangesCall) Return(arg0 []SecretRevisionChange, arg1 error) *MockModelStateGetConsumedSecretURIsWithChangesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelStateGetConsumedSecretURIsWithChangesCall) Do(f func(context.Context, string, ...string) ([]SecretRevisionChange, error)) *MockModelStateGetConsumedSecretURIsWithChangesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelStateGetConsumedSecretURIsWithChangesCall) DoAndReturn(f func(context.Context, string, ...string) ([]SecretRevisionChange, error)) *MockModelStateGetConsumedSecretURIsWithChangesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetOfferDetails mocks base method.
func (m *MockModelState) GetOfferDetails(arg0 context.Context, arg1 internal.OfferFilter) ([]*crossmodelrelation.OfferDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOfferDetails", arg0, arg1)
	ret0, _ := ret[0].([]*crossmodelrelation.OfferDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOfferDetails indicates an expected call of GetOfferDetails.
func (mr *MockModelStateMockRecorder) GetOfferDetails(arg0, arg1 any) *MockModelStateGetOfferDetailsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOfferDetails", reflect.TypeOf((*MockModelState)(nil).GetOfferDetails), arg0, arg1)
	return &MockModelStateGetOfferDetailsCall{Call: call}
}

// MockModelStateGetOfferDetailsCall wrap *gomock.Call
type MockModelStateGetOfferDetailsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelStateGetOfferDetailsCall) Return(arg0 []*crossmodelrelation.OfferDetail, arg1 error) *MockModelStateGetOfferDetailsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelStateGetOfferDetailsCall) Do(f func(context.Context, internal.OfferFilter) ([]*crossmodelrelation.OfferDetail, error)) *MockModelStateGetOfferDetailsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelStateGetOfferDetailsCall) DoAndReturn(f func(context.Context, internal.OfferFilter) ([]*crossmodelrelation.OfferDetail, error)) *MockModelStateGetOfferDetailsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetOfferUUID mocks base method.
func (m *MockModelState) GetOfferUUID(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOfferUUID", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOfferUUID indicates an expected call of GetOfferUUID.
func (mr *MockModelStateMockRecorder) GetOfferUUID(arg0, arg1 any) *MockModelStateGetOfferUUIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOfferUUID", reflect.TypeOf((*MockModelState)(nil).GetOfferUUID), arg0, arg1)
	return &MockModelStateGetOfferUUIDCall{Call: call}
}

// MockModelStateGetOfferUUIDCall wrap *gomock.Call
type MockModelStateGetOfferUUIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelStateGetOfferUUIDCall) Return(arg0 string, arg1 error) *MockModelStateGetOfferUUIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelStateGetOfferUUIDCall) Do(f func(context.Context, string) (string, error)) *MockModelStateGetOfferUUIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelStateGetOfferUUIDCall) DoAndReturn(f func(context.Context, string) (string, error)) *MockModelStateGetOfferUUIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetRemoteApplicationOfferers mocks base method.
func (m *MockModelState) GetRemoteApplicationOfferers(arg0 context.Context) ([]crossmodelrelation.RemoteApplicationOfferer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemoteApplicationOfferers", arg0)
	ret0, _ := ret[0].([]crossmodelrelation.RemoteApplicationOfferer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRemoteApplicationOfferers indicates an expected call of GetRemoteApplicationOfferers.
func (mr *MockModelStateMockRecorder) GetRemoteApplicationOfferers(arg0 any) *MockModelStateGetRemoteApplicationOfferersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemoteApplicationOfferers", reflect.TypeOf((*MockModelState)(nil).GetRemoteApplicationOfferers), arg0)
	return &MockModelStateGetRemoteApplicationOfferersCall{Call: call}
}

// MockModelStateGetRemoteApplicationOfferersCall wrap *gomock.Call
type MockModelStateGetRemoteApplicationOfferersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelStateGetRemoteApplicationOfferersCall) Return(arg0 []crossmodelrelation.RemoteApplicationOfferer, arg1 error) *MockModelStateGetRemoteApplicationOfferersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelStateGetRemoteApplicationOfferersCall) Do(f func(context.Context) ([]crossmodelrelation.RemoteApplicationOfferer, error)) *MockModelStateGetRemoteApplicationOfferersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelStateGetRemoteApplicationOfferersCall) DoAndReturn(f func(context.Context) ([]crossmodelrelation.RemoteApplicationOfferer, error)) *MockModelStateGetRemoteApplicationOfferersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// InitialWatchStatementForConsumedSecretsChanges mocks base method.
func (m *MockModelState) InitialWatchStatementForConsumedSecretsChanges(arg0 string) (string, eventsource.NamespaceQuery) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitialWatchStatementForConsumedSecretsChanges", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(eventsource.NamespaceQuery)
	return ret0, ret1
}

// InitialWatchStatementForConsumedSecretsChanges indicates an expected call of InitialWatchStatementForConsumedSecretsChanges.
func (mr *MockModelStateMockRecorder) InitialWatchStatementForConsumedSecretsChanges(arg0 any) *MockModelStateInitialWatchStatementForConsumedSecretsChangesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitialWatchStatementForConsumedSecretsChanges", reflect.TypeOf((*MockModelState)(nil).InitialWatchStatementForConsumedSecretsChanges), arg0)
	return &MockModelStateInitialWatchStatementForConsumedSecretsChangesCall{Call: call}
}

// MockModelStateInitialWatchStatementForConsumedSecretsChangesCall wrap *gomock.Call
type MockModelStateInitialWatchStatementForConsumedSecretsChangesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelStateInitialWatchStatementForConsumedSecretsChangesCall) Return(arg0 string, arg1 eventsource.NamespaceQuery) *MockModelStateInitialWatchStatementForConsumedSecretsChangesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelStateInitialWatchStatementForConsumedSecretsChangesCall) Do(f func(string) (string, eventsource.NamespaceQuery)) *MockModelStateInitialWatchStatementForConsumedSecretsChangesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelStateInitialWatchStatementForConsumedSecretsChangesCall) DoAndReturn(f func(string) (string, eventsource.NamespaceQuery)) *MockModelStateInitialWatchStatementForConsumedSecretsChangesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// NamespaceRemoteApplicationOfferers mocks base method.
func (m *MockModelState) NamespaceRemoteApplicationOfferers() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NamespaceRemoteApplicationOfferers")
	ret0, _ := ret[0].(string)
	return ret0
}

// NamespaceRemoteApplicationOfferers indicates an expected call of NamespaceRemoteApplicationOfferers.
func (mr *MockModelStateMockRecorder) NamespaceRemoteApplicationOfferers() *MockModelStateNamespaceRemoteApplicationOfferersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NamespaceRemoteApplicationOfferers", reflect.TypeOf((*MockModelState)(nil).NamespaceRemoteApplicationOfferers))
	return &MockModelStateNamespaceRemoteApplicationOfferersCall{Call: call}
}

// MockModelStateNamespaceRemoteApplicationOfferersCall wrap *gomock.Call
type MockModelStateNamespaceRemoteApplicationOfferersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelStateNamespaceRemoteApplicationOfferersCall) Return(arg0 string) *MockModelStateNamespaceRemoteApplicationOfferersCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelStateNamespaceRemoteApplicationOfferersCall) Do(f func() string) *MockModelStateNamespaceRemoteApplicationOfferersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelStateNamespaceRemoteApplicationOfferersCall) DoAndReturn(f func() string) *MockModelStateNamespaceRemoteApplicationOfferersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveMacaroonForRelation mocks base method.
func (m *MockModelState) SaveMacaroonForRelation(arg0 context.Context, arg1 string, arg2 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMacaroonForRelation", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMacaroonForRelation indicates an expected call of SaveMacaroonForRelation.
func (mr *MockModelStateMockRecorder) SaveMacaroonForRelation(arg0, arg1, arg2 any) *MockModelStateSaveMacaroonForRelationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMacaroonForRelation", reflect.TypeOf((*MockModelState)(nil).SaveMacaroonForRelation), arg0, arg1, arg2)
	return &MockModelStateSaveMacaroonForRelationCall{Call: call}
}

// MockModelStateSaveMacaroonForRelationCall wrap *gomock.Call
type MockModelStateSaveMacaroonForRelationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelStateSaveMacaroonForRelationCall) Return(arg0 error) *MockModelStateSaveMacaroonForRelationCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelStateSaveMacaroonForRelationCall) Do(f func(context.Context, string, []byte) error) *MockModelStateSaveMacaroonForRelationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelStateSaveMacaroonForRelationCall) DoAndReturn(f func(context.Context, string, []byte) error) *MockModelStateSaveMacaroonForRelationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateOffer mocks base method.
func (m *MockModelState) UpdateOffer(arg0 context.Context, arg1 string, arg2 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOffer", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOffer indicates an expected call of UpdateOffer.
func (mr *MockModelStateMockRecorder) UpdateOffer(arg0, arg1, arg2 any) *MockModelStateUpdateOfferCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOffer", reflect.TypeOf((*MockModelState)(nil).UpdateOffer), arg0, arg1, arg2)
	return &MockModelStateUpdateOfferCall{Call: call}
}

// MockModelStateUpdateOfferCall wrap *gomock.Call
type MockModelStateUpdateOfferCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelStateUpdateOfferCall) Return(arg0 error) *MockModelStateUpdateOfferCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelStateUpdateOfferCall) Do(f func(context.Context, string, []string) error) *MockModelStateUpdateOfferCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelStateUpdateOfferCall) DoAndReturn(f func(context.Context, string, []string) error) *MockModelStateUpdateOfferCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockModelMigrationState is a mock of ModelMigrationState interface.
type MockModelMigrationState struct {
	ctrl     *gomock.Controller
	recorder *MockModelMigrationStateMockRecorder
}

// MockModelMigrationStateMockRecorder is the mock recorder for MockModelMigrationState.
type MockModelMigrationStateMockRecorder struct {
	mock *MockModelMigrationState
}

// NewMockModelMigrationState creates a new mock instance.
func NewMockModelMigrationState(ctrl *gomock.Controller) *MockModelMigrationState {
	mock := &MockModelMigrationState{ctrl: ctrl}
	mock.recorder = &MockModelMigrationStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelMigrationState) EXPECT() *MockModelMigrationStateMockRecorder {
	return m.recorder
}

// ImportOffers mocks base method.
func (m *MockModelMigrationState) ImportOffers(arg0 context.Context, arg1 []crossmodelrelation.OfferImport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportOffers", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImportOffers indicates an expected call of ImportOffers.
func (mr *MockModelMigrationStateMockRecorder) ImportOffers(arg0, arg1 any) *MockModelMigrationStateImportOffersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportOffers", reflect.TypeOf((*MockModelMigrationState)(nil).ImportOffers), arg0, arg1)
	return &MockModelMigrationStateImportOffersCall{Call: call}
}

// MockModelMigrationStateImportOffersCall wrap *gomock.Call
type MockModelMigrationStateImportOffersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelMigrationStateImportOffersCall) Return(arg0 error) *MockModelMigrationStateImportOffersCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelMigrationStateImportOffersCall) Do(f func(context.Context, []crossmodelrelation.OfferImport) error) *MockModelMigrationStateImportOffersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelMigrationStateImportOffersCall) DoAndReturn(f func(context.Context, []crossmodelrelation.OfferImport) error) *MockModelMigrationStateImportOffersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockModelRemoteApplicationState is a mock of ModelRemoteApplicationState interface.
type MockModelRemoteApplicationState struct {
	ctrl     *gomock.Controller
	recorder *MockModelRemoteApplicationStateMockRecorder
}

// MockModelRemoteApplicationStateMockRecorder is the mock recorder for MockModelRemoteApplicationState.
type MockModelRemoteApplicationStateMockRecorder struct {
	mock *MockModelRemoteApplicationState
}

// NewMockModelRemoteApplicationState creates a new mock instance.
func NewMockModelRemoteApplicationState(ctrl *gomock.Controller) *MockModelRemoteApplicationState {
	mock := &MockModelRemoteApplicationState{ctrl: ctrl}
	mock.recorder = &MockModelRemoteApplicationStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelRemoteApplicationState) EXPECT() *MockModelRemoteApplicationStateMockRecorder {
	return m.recorder
}

// AddRemoteApplicationConsumer mocks base method.
func (m *MockModelRemoteApplicationState) AddRemoteApplicationConsumer(arg0 context.Context, arg1 string, arg2 crossmodelrelation.AddRemoteApplicationConsumerArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRemoteApplicationConsumer", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRemoteApplicationConsumer indicates an expected call of AddRemoteApplicationConsumer.
func (mr *MockModelRemoteApplicationStateMockRecorder) AddRemoteApplicationConsumer(arg0, arg1, arg2 any) *MockModelRemoteApplicationStateAddRemoteApplicationConsumerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRemoteApplicationConsumer", reflect.TypeOf((*MockModelRemoteApplicationState)(nil).AddRemoteApplicationConsumer), arg0, arg1, arg2)
	return &MockModelRemoteApplicationStateAddRemoteApplicationConsumerCall{Call: call}
}

// MockModelRemoteApplicationStateAddRemoteApplicationConsumerCall wrap *gomock.Call
type MockModelRemoteApplicationStateAddRemoteApplicationConsumerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelRemoteApplicationStateAddRemoteApplicationConsumerCall) Return(arg0 error) *MockModelRemoteApplicationStateAddRemoteApplicationConsumerCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelRemoteApplicationStateAddRemoteApplicationConsumerCall) Do(f func(context.Context, string, crossmodelrelation.AddRemoteApplicationConsumerArgs) error) *MockModelRemoteApplicationStateAddRemoteApplicationConsumerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelRemoteApplicationStateAddRemoteApplicationConsumerCall) DoAndReturn(f func(context.Context, string, crossmodelrelation.AddRemoteApplicationConsumerArgs) error) *MockModelRemoteApplicationStateAddRemoteApplicationConsumerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddRemoteApplicationOfferer mocks base method.
func (m *MockModelRemoteApplicationState) AddRemoteApplicationOfferer(arg0 context.Context, arg1 string, arg2 crossmodelrelation.AddRemoteApplicationOffererArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRemoteApplicationOfferer", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRemoteApplicationOfferer indicates an expected call of AddRemoteApplicationOfferer.
func (mr *MockModelRemoteApplicationStateMockRecorder) AddRemoteApplicationOfferer(arg0, arg1, arg2 any) *MockModelRemoteApplicationStateAddRemoteApplicationOffererCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRemoteApplicationOfferer", reflect.TypeOf((*MockModelRemoteApplicationState)(nil).AddRemoteApplicationOfferer), arg0, arg1, arg2)
	return &MockModelRemoteApplicationStateAddRemoteApplicationOffererCall{Call: call}
}

// MockModelRemoteApplicationStateAddRemoteApplicationOffererCall wrap *gomock.Call
type MockModelRemoteApplicationStateAddRemoteApplicationOffererCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelRemoteApplicationStateAddRemoteApplicationOffererCall) Return(arg0 error) *MockModelRemoteApplicationStateAddRemoteApplicationOffererCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelRemoteApplicationStateAddRemoteApplicationOffererCall) Do(f func(context.Context, string, crossmodelrelation.AddRemoteApplicationOffererArgs) error) *MockModelRemoteApplicationStateAddRemoteApplicationOffererCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelRemoteApplicationStateAddRemoteApplicationOffererCall) DoAndReturn(f func(context.Context, string, crossmodelrelation.AddRemoteApplicationOffererArgs) error) *MockModelRemoteApplicationStateAddRemoteApplicationOffererCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetConsumedSecretURIsWithChanges mocks base method.
func (m *MockModelRemoteApplicationState) GetConsumedSecretURIsWithChanges(arg0 context.Context, arg1 string, arg2 ...string) ([]SecretRevisionChange, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetConsumedSecretURIsWithChanges", varargs...)
	ret0, _ := ret[0].([]SecretRevisionChange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConsumedSecretURIsWithChanges indicates an expected call of GetConsumedSecretURIsWithChanges.
func (mr *MockModelRemoteApplicationStateMockRecorder) GetConsumedSecretURIsWithChanges(arg0, arg1 any, arg2 ...any) *MockModelRemoteApplicationStateGetConsumedSecretURIsWithChangesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsumedSecretURIsWithChanges", reflect.TypeOf((*MockModelRemoteApplicationState)(nil).GetConsumedSecretURIsWithChanges), varargs...)
	return &MockModelRemoteApplicationStateGetConsumedSecretURIsWithChangesCall{Call: call}
}

// MockModelRemoteApplicationStateGetConsumedSecretURIsWithChangesCall wrap *gomock.Call
type MockModelRemoteApplicationStateGetConsumedSecretURIsWithChangesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelRemoteApplicationStateGetConsumedSecretURIsWithChangesCall) Return(arg0 []SecretRevisionChange, arg1 error) *MockModelRemoteApplicationStateGetConsumedSecretURIsWithChangesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelRemoteApplicationStateGetConsumedSecretURIsWithChangesCall) Do(f func(context.Context, string, ...string) ([]SecretRevisionChange, error)) *MockModelRemoteApplicationStateGetConsumedSecretURIsWithChangesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelRemoteApplicationStateGetConsumedSecretURIsWithChangesCall) DoAndReturn(f func(context.Context, string, ...string) ([]SecretRevisionChange, error)) *MockModelRemoteApplicationStateGetConsumedSecretURIsWithChangesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetRemoteApplicationOfferers mocks base method.
func (m *MockModelRemoteApplicationState) GetRemoteApplicationOfferers(arg0 context.Context) ([]crossmodelrelation.RemoteApplicationOfferer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemoteApplicationOfferers", arg0)
	ret0, _ := ret[0].([]crossmodelrelation.RemoteApplicationOfferer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRemoteApplicationOfferers indicates an expected call of GetRemoteApplicationOfferers.
func (mr *MockModelRemoteApplicationStateMockRecorder) GetRemoteApplicationOfferers(arg0 any) *MockModelRemoteApplicationStateGetRemoteApplicationOfferersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemoteApplicationOfferers", reflect.TypeOf((*MockModelRemoteApplicationState)(nil).GetRemoteApplicationOfferers), arg0)
	return &MockModelRemoteApplicationStateGetRemoteApplicationOfferersCall{Call: call}
}

// MockModelRemoteApplicationStateGetRemoteApplicationOfferersCall wrap *gomock.Call
type MockModelRemoteApplicationStateGetRemoteApplicationOfferersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelRemoteApplicationStateGetRemoteApplicationOfferersCall) Return(arg0 []crossmodelrelation.RemoteApplicationOfferer, arg1 error) *MockModelRemoteApplicationStateGetRemoteApplicationOfferersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelRemoteApplicationStateGetRemoteApplicationOfferersCall) Do(f func(context.Context) ([]crossmodelrelation.RemoteApplicationOfferer, error)) *MockModelRemoteApplicationStateGetRemoteApplicationOfferersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelRemoteApplicationStateGetRemoteApplicationOfferersCall) DoAndReturn(f func(context.Context) ([]crossmodelrelation.RemoteApplicationOfferer, error)) *MockModelRemoteApplicationStateGetRemoteApplicationOfferersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// InitialWatchStatementForConsumedSecretsChanges mocks base method.
func (m *MockModelRemoteApplicationState) InitialWatchStatementForConsumedSecretsChanges(arg0 string) (string, eventsource.NamespaceQuery) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitialWatchStatementForConsumedSecretsChanges", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(eventsource.NamespaceQuery)
	return ret0, ret1
}

// InitialWatchStatementForConsumedSecretsChanges indicates an expected call of InitialWatchStatementForConsumedSecretsChanges.
func (mr *MockModelRemoteApplicationStateMockRecorder) InitialWatchStatementForConsumedSecretsChanges(arg0 any) *MockModelRemoteApplicationStateInitialWatchStatementForConsumedSecretsChangesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitialWatchStatementForConsumedSecretsChanges", reflect.TypeOf((*MockModelRemoteApplicationState)(nil).InitialWatchStatementForConsumedSecretsChanges), arg0)
	return &MockModelRemoteApplicationStateInitialWatchStatementForConsumedSecretsChangesCall{Call: call}
}

// MockModelRemoteApplicationStateInitialWatchStatementForConsumedSecretsChangesCall wrap *gomock.Call
type MockModelRemoteApplicationStateInitialWatchStatementForConsumedSecretsChangesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelRemoteApplicationStateInitialWatchStatementForConsumedSecretsChangesCall) Return(arg0 string, arg1 eventsource.NamespaceQuery) *MockModelRemoteApplicationStateInitialWatchStatementForConsumedSecretsChangesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelRemoteApplicationStateInitialWatchStatementForConsumedSecretsChangesCall) Do(f func(string) (string, eventsource.NamespaceQuery)) *MockModelRemoteApplicationStateInitialWatchStatementForConsumedSecretsChangesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelRemoteApplicationStateInitialWatchStatementForConsumedSecretsChangesCall) DoAndReturn(f func(string) (string, eventsource.NamespaceQuery)) *MockModelRemoteApplicationStateInitialWatchStatementForConsumedSecretsChangesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// NamespaceRemoteApplicationOfferers mocks base method.
func (m *MockModelRemoteApplicationState) NamespaceRemoteApplicationOfferers() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NamespaceRemoteApplicationOfferers")
	ret0, _ := ret[0].(string)
	return ret0
}

// NamespaceRemoteApplicationOfferers indicates an expected call of NamespaceRemoteApplicationOfferers.
func (mr *MockModelRemoteApplicationStateMockRecorder) NamespaceRemoteApplicationOfferers() *MockModelRemoteApplicationStateNamespaceRemoteApplicationOfferersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NamespaceRemoteApplicationOfferers", reflect.TypeOf((*MockModelRemoteApplicationState)(nil).NamespaceRemoteApplicationOfferers))
	return &MockModelRemoteApplicationStateNamespaceRemoteApplicationOfferersCall{Call: call}
}

// MockModelRemoteApplicationStateNamespaceRemoteApplicationOfferersCall wrap *gomock.Call
type MockModelRemoteApplicationStateNamespaceRemoteApplicationOfferersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelRemoteApplicationStateNamespaceRemoteApplicationOfferersCall) Return(arg0 string) *MockModelRemoteApplicationStateNamespaceRemoteApplicationOfferersCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelRemoteApplicationStateNamespaceRemoteApplicationOfferersCall) Do(f func() string) *MockModelRemoteApplicationStateNamespaceRemoteApplicationOfferersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelRemoteApplicationStateNamespaceRemoteApplicationOfferersCall) DoAndReturn(f func() string) *MockModelRemoteApplicationStateNamespaceRemoteApplicationOfferersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveMacaroonForRelation mocks base method.
func (m *MockModelRemoteApplicationState) SaveMacaroonForRelation(arg0 context.Context, arg1 string, arg2 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMacaroonForRelation", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMacaroonForRelation indicates an expected call of SaveMacaroonForRelation.
func (mr *MockModelRemoteApplicationStateMockRecorder) SaveMacaroonForRelation(arg0, arg1, arg2 any) *MockModelRemoteApplicationStateSaveMacaroonForRelationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMacaroonForRelation", reflect.TypeOf((*MockModelRemoteApplicationState)(nil).SaveMacaroonForRelation), arg0, arg1, arg2)
	return &MockModelRemoteApplicationStateSaveMacaroonForRelationCall{Call: call}
}

// MockModelRemoteApplicationStateSaveMacaroonForRelationCall wrap *gomock.Call
type MockModelRemoteApplicationStateSaveMacaroonForRelationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelRemoteApplicationStateSaveMacaroonForRelationCall) Return(arg0 error) *MockModelRemoteApplicationStateSaveMacaroonForRelationCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelRemoteApplicationStateSaveMacaroonForRelationCall) Do(f func(context.Context, string, []byte) error) *MockModelRemoteApplicationStateSaveMacaroonForRelationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelRemoteApplicationStateSaveMacaroonForRelationCall) DoAndReturn(f func(context.Context, string, []byte) error) *MockModelRemoteApplicationStateSaveMacaroonForRelationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockWatcherFactory is a mock of WatcherFactory interface.
type MockWatcherFactory struct {
	ctrl     *gomock.Controller
	recorder *MockWatcherFactoryMockRecorder
}

// MockWatcherFactoryMockRecorder is the mock recorder for MockWatcherFactory.
type MockWatcherFactoryMockRecorder struct {
	mock *MockWatcherFactory
}

// NewMockWatcherFactory creates a new mock instance.
func NewMockWatcherFactory(ctrl *gomock.Controller) *MockWatcherFactory {
	mock := &MockWatcherFactory{ctrl: ctrl}
	mock.recorder = &MockWatcherFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatcherFactory) EXPECT() *MockWatcherFactoryMockRecorder {
	return m.recorder
}

// NewNamespaceWatcher mocks base method.
func (m *MockWatcherFactory) NewNamespaceWatcher(arg0 context.Context, arg1 eventsource.NamespaceQuery, arg2 string, arg3 eventsource.FilterOption, arg4 ...eventsource.FilterOption) (watcher.Watcher[[]string], error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewNamespaceWatcher", varargs...)
	ret0, _ := ret[0].(watcher.Watcher[[]string])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewNamespaceWatcher indicates an expected call of NewNamespaceWatcher.
func (mr *MockWatcherFactoryMockRecorder) NewNamespaceWatcher(arg0, arg1, arg2, arg3 any, arg4 ...any) *MockWatcherFactoryNewNamespaceWatcherCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3}, arg4...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewNamespaceWatcher", reflect.TypeOf((*MockWatcherFactory)(nil).NewNamespaceWatcher), varargs...)
	return &MockWatcherFactoryNewNamespaceWatcherCall{Call: call}
}

// MockWatcherFactoryNewNamespaceWatcherCall wrap *gomock.Call
type MockWatcherFactoryNewNamespaceWatcherCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWatcherFactoryNewNamespaceWatcherCall) Return(arg0 watcher.Watcher[[]string], arg1 error) *MockWatcherFactoryNewNamespaceWatcherCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWatcherFactoryNewNamespaceWatcherCall) Do(f func(context.Context, eventsource.NamespaceQuery, string, eventsource.FilterOption, ...eventsource.FilterOption) (watcher.Watcher[[]string], error)) *MockWatcherFactoryNewNamespaceWatcherCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWatcherFactoryNewNamespaceWatcherCall) DoAndReturn(f func(context.Context, eventsource.NamespaceQuery, string, eventsource.FilterOption, ...eventsource.FilterOption) (watcher.Watcher[[]string], error)) *MockWatcherFactoryNewNamespaceWatcherCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// NewNotifyWatcher mocks base method.
func (m *MockWatcherFactory) NewNotifyWatcher(arg0 context.Context, arg1 string, arg2 eventsource.FilterOption, arg3 ...eventsource.FilterOption) (watcher.Watcher[struct{}], error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewNotifyWatcher", varargs...)
	ret0, _ := ret[0].(watcher.Watcher[struct{}])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewNotifyWatcher indicates an expected call of NewNotifyWatcher.
func (mr *MockWatcherFactoryMockRecorder) NewNotifyWatcher(arg0, arg1, arg2 any, arg3 ...any) *MockWatcherFactoryNewNotifyWatcherCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewNotifyWatcher", reflect.TypeOf((*MockWatcherFactory)(nil).NewNotifyWatcher), varargs...)
	return &MockWatcherFactoryNewNotifyWatcherCall{Call: call}
}

// MockWatcherFactoryNewNotifyWatcherCall wrap *gomock.Call
type MockWatcherFactoryNewNotifyWatcherCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWatcherFactoryNewNotifyWatcherCall) Return(arg0 watcher.Watcher[struct{}], arg1 error) *MockWatcherFactoryNewNotifyWatcherCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWatcherFactoryNewNotifyWatcherCall) Do(f func(context.Context, string, eventsource.FilterOption, ...eventsource.FilterOption) (watcher.Watcher[struct{}], error)) *MockWatcherFactoryNewNotifyWatcherCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWatcherFactoryNewNotifyWatcherCall) DoAndReturn(f func(context.Context, string, eventsource.FilterOption, ...eventsource.FilterOption) (watcher.Watcher[struct{}], error)) *MockWatcherFactoryNewNotifyWatcherCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
