// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/domain/controller/service (interfaces: State)
//
// Generated by this command:
//
//	mockgen -typed -package service -destination package_mock_test.go github.com/juju/juju/domain/controller/service State
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	model "github.com/juju/juju/core/model"
	gomock "go.uber.org/mock/gomock"
)

// MockState is a mock of State interface.
type MockState struct {
	ctrl     *gomock.Controller
	recorder *MockStateMockRecorder
}

// MockStateMockRecorder is the mock recorder for MockState.
type MockStateMockRecorder struct {
	mock *MockState
}

// NewMockState creates a new mock instance.
func NewMockState(ctrl *gomock.Controller) *MockState {
	mock := &MockState{ctrl: ctrl}
	mock.recorder = &MockStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockState) EXPECT() *MockStateMockRecorder {
	return m.recorder
}

// Controller mocks base method.
func (m *MockState) Controller(arg0 context.Context) (string, model.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Controller", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(model.UUID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Controller indicates an expected call of Controller.
func (mr *MockStateMockRecorder) Controller(arg0 any) *MockStateControllerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Controller", reflect.TypeOf((*MockState)(nil).Controller), arg0)
	return &MockStateControllerCall{Call: call}
}

// MockStateControllerCall wrap *gomock.Call
type MockStateControllerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateControllerCall) Return(arg0 string, arg1 model.UUID, arg2 error) *MockStateControllerCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateControllerCall) Do(f func(context.Context) (string, model.UUID, error)) *MockStateControllerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateControllerCall) DoAndReturn(f func(context.Context) (string, model.UUID, error)) *MockStateControllerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
